	SUBROUTINE CONVERGENCE
!
	USE ISOPARAMETRIC_MESH
	USE CRACKS_DUAL_BEM
	USE MATERIALS
    USE SUB_REGIONS_INTERFACES
	USE ANALYSIS
	USE REMESHING
!
	IMPLICIT NONE 
!
	INTEGER::I,J,K,L,NEN
!
    REAL*8::E,Nu,U_EXT(3),U_NUM(3),VALUES[ALLOCATABLE](:,:),COEFFICIENTS[ALLOCATABLE](:,:),PHI[ALLOCATABLE](:),DPHI[ALLOCATABLE](:,:),D2PHI[ALLOCATABLE](:,:,:),QSIW_GAUSS[ALLOCATABLE](:,:),VJC(3),DVJC(3,2),JC,ETA(3),X,Y,Z 
    REAL*8::U_EXTxU_EXT,U_ERRORxU_ERROR,RELATIVE_ERROR
!
    U_EXTxU_EXT=0.D0
    U_ERRORxU_ERROR=0.D0
!            
    ALLOCATE(QSIW_GAUSS(N_GAUSSPOINTS,2))
    CALL GAUSS_POINTS(N_GAUSSPOINTS,QSIW_GAUSS)
    
   	DO I=1,N_ELEM
   	    IF(CRACKED_ELEM(I).EQ."UNCRACKED")THEN
   	        E=EMP(ND(I),1)
            Nu=EMP(ND(I),2)
   	        NEN=ELEM_TYPE(I)*ORDER_ELEM(I)+(ELEM_TYPE(I)-3)*(ORDER_ELEM(I)-1)*POL_FAMILY(I)
   	        ALLOCATE(VALUES(NEN,3),COEFFICIENTS(NEN,NEN),PHI(NEN))
   	        CALL SHAPE_FUNCTIONS_COEFFICIENTS(I,NEN,COEFFICIENTS)
   	        DO J=1,NEN
		        VALUES(J,1)=COORD_NODES(NODES_CONNECTIVITY(I,J),1)
	            VALUES(J,2)=COORD_NODES(NODES_CONNECTIVITY(I,J),2)
	            VALUES(J,3)=COORD_NODES(NODES_CONNECTIVITY(I,J),3)
	        ENDDO
			DO J=1,N_GAUSSPOINTS
			    DO K=1,N_GAUSSPOINTS
			        CALL SHAPE_FUNCTIONS(1,QSIW_GAUSS(J,1),QSIW_GAUSS(K,1),NEN,VALUES,COEFFICIENTS,X,Y,Z,PHI,DPHI,D2PHI)
			        U_EXT(1)=-Nu*X/E
                    U_EXT(2)=-Nu*Y/E
                    U_EXT(3)=Z/E
                    CALL NORMAL_OUTWARD(NEN,VALUES,QSIW_GAUSS(J,1),QSIW_GAUSS(K,1),ETA,VJC,DVJC,JC)
                    U_EXTxU_EXT=U_EXTxU_EXT+(U_EXT(1)**2+U_EXT(2)**2+U_EXT(3)**2)*QSIW_GAUSS(J,2)*QSIW_GAUSS(K,2)*JC                    
			        CALL SHAPE_FUNCTIONS(2,QSIW_GAUSS(J,1),QSIW_GAUSS(K,1),NEN,VALUES,COEFFICIENTS,X,Y,Z,PHI,DPHI,D2PHI)
			        U_NUM=0.D0
			        DO L=1,NEN
			            U_NUM(1)=U_NUM(1)+PHI(L)*U(3*(COLLOCPOINTS_CONNECTIVITY(I,L))-2)
			            U_NUM(2)=U_NUM(2)+PHI(L)*U(3*(COLLOCPOINTS_CONNECTIVITY(I,L))-1)
			            U_NUM(3)=U_NUM(3)+PHI(L)*U(3*(COLLOCPOINTS_CONNECTIVITY(I,L)))
			        ENDDO
			        U_ERRORxU_ERROR=U_ERRORxU_ERROR+((U_NUM(1)-U_EXT(1))**2+(U_NUM(2)-U_EXT(2))**2+(U_NUM(3)-U_EXT(3))**2)*QSIW_GAUSS(J,2)*QSIW_GAUSS(K,2)*JC
			    ENDDO
			ENDDO
			DEALLOCATE(VALUES,COEFFICIENTS,PHI)
        ENDIF
    ENDDO
!
    RELATIVE_ERROR=DSQRT(U_ERRORxU_ERROR/U_EXTxU_EXT)    
!
    OPEN(33,file='CONVERGENCE.txt',status='unknown')
    WRITE(33,*)'NUMBER OF COLLOCATION POINTS       DISPLACEMENT RELATIVE ERROR'    
    WRITE(33,100) N_COLLOCPOINTS,U_EXTxU_EXT,U_ERRORxU_ERROR,RELATIVE_ERROR
	CLOSE(33)    
!    		
    100	FORMAT(I5,8x,F14.9,8x,F14.9,8x,F14.9)    
!      
    END SUBROUTINE