	SUBROUTINE DISPLACEMENT_EXTRAPOLATION_TECHNIQUE(STEP)
!	
    USE ISOPARAMETRIC_MESH
    USE MATERIALS
	USE CRACKS_DUAL_BEM
	USE SUB_REGIONS_INTERFACES
	USE ANALYSIS
	USE REMESHING
	USE PROPAGATION	   
	USE FATIGUE
!
    IMPLICIT NONE
    INTEGER::I,J,K,II,JJ,KK,ELEMENT,LOCAL_NUMBER,CP_S1,CP_S2,CP_H1,CP_H2,NEN,CONT,STEP 
!    
    REAL*8::THETA,GTHETA,GTHETA_AUX,DX,DY,DZ,R,R1,R2,COD1,COD2,CSD1,CSD2,CTD1,CTD2,KI1,KI2,KII1,KII2,KIII1,KIII2,E,Nu,KIC,PI
    REAL*8::VALUES[ALLOCATABLE](:,:),COEFFICIENTS[ALLOCATABLE](:,:),PHI[ALLOCATABLE](:),DPHI[ALLOCATABLE](:,:),D2PHI[ALLOCATABLE](:,:,:) 
!
    CHARACTER(40)::NOME	     
!
	PI=DACOS(-1.D0)
    N_CRACKTIPS=0  
    DO I=1,N_COLLOCPOINTS
        IF(CRACK_TIP(I).EQ.1.AND.DUAL_BEM(I).EQ."S")THEN
            N_CRACKTIPS=N_CRACKTIPS+1
        ENDIF
        IF(CRACK_TIP(I).EQ.3.AND.DUAL_BEM(I).EQ."S")THEN
            N_CRACKTIPS=N_CRACKTIPS+1
        ENDIF        
    ENDDO
    
    ALLOCATE(COORD_CRACKTIP(N_CRACKTIPS,3),KI(N_CRACKTIPS),KII(N_CRACKTIPS),KIII(N_CRACKTIPS),COD(N_CRACKTIPS),CSD(N_CRACKTIPS),CTD(N_CRACKTIPS),THETAP(N_CRACKTIPS),PHIP(N_CRACKTIPS),Keq(N_CRACKTIPS),Gmax(N_CRACKTIPS),CRACK_INCREMENT(N_CRACKTIPS),VERTICAL_INCREMENT(N_CRACKTIPS),CRACKTIP_COLLOCPOINTS(N_CRACKTIPS))
! --------------------------------------------------------------------------------------------------------------------------------------------------
!   DISPLACEMENT EXTRAPOLATION TECHNIQUE: COMPUTING THE STRESS INTENSITY FACTORS KI, KII, KIII
! --------------------------------------------------------------------------------------------------------------------------------------------------   
    CONT=0 
    PI=DACOS(-1.D0)
    DO I=1,N_COLLOCPOINTS
        IF(CRACK_TIP(I).EQ.1.AND.DUAL_BEM(I).EQ."S")THEN
            CP_S1=I
            CONT=CONT+1
!            
            DO J=1,N_ELEM
                NEN=ELEM_TYPE(J)*ORDER_ELEM(J)+(ELEM_TYPE(J)-3)*(ORDER_ELEM(J)-1)*POL_FAMILY(J)
                DO K=1,NEN
                    IF(COLLOCPOINTS_CONNECTIVITY(J,K).EQ.CP_S1)THEN
                        ELEMENT=J
                        LOCAL_NUMBER=K                    
                    ENDIF
                    IF(DUAL_BEM(COLLOCPOINTS_CONNECTIVITY(J,K)).EQ.'H')THEN
                        DX=COORD_COLLOCPOINTS(COLLOCPOINTS_CONNECTIVITY(J,K),1)-COORD_COLLOCPOINTS(CP_S1,1)
			            DY=COORD_COLLOCPOINTS(COLLOCPOINTS_CONNECTIVITY(J,K),2)-COORD_COLLOCPOINTS(CP_S1,2)
	                    DZ=COORD_COLLOCPOINTS(COLLOCPOINTS_CONNECTIVITY(J,K),3)-COORD_COLLOCPOINTS(CP_S1,3)
			            R=DSQRT(DX*DX+DY*DY+DZ*DZ)
			            IF(R.LE.1.E-12) THEN
				            CP_H1=COLLOCPOINTS_CONNECTIVITY(J,K)
				        ENDIF
                    ENDIF
                ENDDO
            ENDDO
!            
            E=EMP(ND(ELEMENT),1)
            Nu=EMP(ND(ELEMENT),2)
            CRACKTIP_COLLOCPOINTS(CONT)=COLLOCPOINTS_CONNECTIVITY(ELEMENT,LOCAL_NUMBER)
!            
            NEN=ELEM_TYPE(ELEMENT)*ORDER_ELEM(ELEMENT)+(ELEM_TYPE(ELEMENT)-3)*(ORDER_ELEM(ELEMENT)-1)*POL_FAMILY(ELEMENT)
            ALLOCATE(VALUES(NEN,3))	
	        DO K=1,NEN
		        VALUES(K,1)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),1)
		        VALUES(K,2)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),2)
		        VALUES(K,3)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),3)
	        ENDDO 
	        SELECT CASE(LOCAL_NUMBER)
	        CASE(1)
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN                      	            
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                                             
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)  
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                               
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                    
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ) 
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                          
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ) 
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                          
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                          
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)    
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                      
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ) 
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                                                                  
                ELSE
                    CALL SHAPE_FUNCTIONS(1,-0.8D0,-1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                        
                ENDIF  
            CASE(2)
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN                                    
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)    
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                                       
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)  
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                             
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)  
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                              
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ) 
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                    
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                        
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)  
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                      
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)  
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                      
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                    
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                                                                                        
                ELSE
                    CALL SHAPE_FUNCTIONS(1,0.8D0,-1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)  
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                    
                ENDIF
            CASE(3)
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)   
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                                          
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)  
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                      
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                              
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)                    
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                      
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                              
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                      
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)                       
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                                                                 
                ELSE
                    CALL SHAPE_FUNCTIONS(1,1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ) 
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                      
                ENDIF
            CASE(4)                                     
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                                              
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)            
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)    
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                              
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)       
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)                     
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)       
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ) 
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ) 
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                                                                                      
                ELSE
                    CALL SHAPE_FUNCTIONS(1,-0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ) 
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                      
                ENDIF             	        	        
	        ENDSELECT
!
            DO J=1,N_ELEM
                NEN=ELEM_TYPE(J)*ORDER_ELEM(J)+(ELEM_TYPE(J)-3)*(ORDER_ELEM(J)-1)*POL_FAMILY(J)
                DO K=1,NEN
                    IF(COLLOCPOINTS_CONNECTIVITY(J,K).EQ.CP_S2)THEN
                        ELEMENT=J
                        LOCAL_NUMBER=K                    
                    ENDIF
                    IF(DUAL_BEM(COLLOCPOINTS_CONNECTIVITY(J,K)).EQ.'H')THEN
                        DX=COORD_COLLOCPOINTS(COLLOCPOINTS_CONNECTIVITY(J,K),1)-COORD_COLLOCPOINTS(CP_S2,1)
			            DY=COORD_COLLOCPOINTS(COLLOCPOINTS_CONNECTIVITY(J,K),2)-COORD_COLLOCPOINTS(CP_S2,2)
	                    DZ=COORD_COLLOCPOINTS(COLLOCPOINTS_CONNECTIVITY(J,K),3)-COORD_COLLOCPOINTS(CP_S2,3)
			            R=DSQRT(DX*DX+DY*DY+DZ*DZ)
			            IF(R.LE.1.E-12) THEN
				            CP_H2=COLLOCPOINTS_CONNECTIVITY(J,K)
				        ENDIF
                    ENDIF
                ENDDO
            ENDDO	           
!
            COD1=-U(3*CP_S1-2)-U(3*CP_H1-2)          
            CSD1=-U(3*CP_S1-1)-U(3*CP_H1-1)        
            CTD1=-U(3*CP_S1)+U(3*CP_H1) 	
!
            KI1=(E/(4*(1-Nu**2)))*DSQRT(PI/(2*R1))*COD1
            KII1=(E/(4*(1-Nu**2)))*DSQRT(PI/(2*R1))*CSD1
            KIII1=(E/(4*(1+Nu)))*DSQRT(PI/(2*R1))*CTD1  
!
            COD2=-U(3*CP_S2-2)-U(3*CP_H2-2)          
            CSD2=-U(3*CP_S2-1)-U(3*CP_H2-1)        
            CTD2=-U(3*CP_S2)+U(3*CP_H2) 	
!
            KI2=(E/(4*(1-Nu**2)))*DSQRT(PI/(2*R2))*COD2
            KII2=(E/(4*(1-Nu**2)))*DSQRT(PI/(2*R2))*CSD2
            KIII2=(E/(4*(1+Nu)))*DSQRT(PI/(2*R2))*CTD2 
!
!            COD(CONT)=COD2 
!            CSD(CONT)=CSD2        
!            CTD(CONT)=CTD2
!!                              
!            KI(CONT)=KI2
!            KII(CONT)=KII2
!            KIII(CONT)=KIII2                                     
!                        
            COD(CONT)=(COD1*(R1-R2)-R1*(COD1-COD2))/(R1-R2)        
            CSD(CONT)=(CSD1*(R1-R2)-R1*(CSD1-CSD2))/(R1-R2)          
            CTD(CONT)=(CTD1*(R1-R2)-R1*(CTD1-CTD2))/(R1-R2)
!                              
            KI(CONT)=(KI1*(R1-R2)-R1*(KI1-KI2))/(R1-R2)
            KII(CONT)=(KII1*(R1-R2)-R1*(KII1-KII2))/(R1-R2)
            KIII(CONT)=(KIII1*(R1-R2)-R1*(KIII1-KIII2))/(R1-R2) 
! 	                                          
            DEALLOCATE(VALUES)                    
        ELSE IF(CRACK_TIP(I).EQ.3.AND.DUAL_BEM(I).EQ."S")THEN
            CP_S1=I
            CONT=CONT+1
!            
            DO J=1,N_ELEM
                NEN=ELEM_TYPE(J)*ORDER_ELEM(J)+(ELEM_TYPE(J)-3)*(ORDER_ELEM(J)-1)*POL_FAMILY(J)
                DO K=1,NEN
                    IF(COLLOCPOINTS_CONNECTIVITY(J,K).EQ.CP_S1)THEN
                        ELEMENT=J
                        LOCAL_NUMBER=K                    
                    ENDIF
                    IF(DUAL_BEM(COLLOCPOINTS_CONNECTIVITY(J,K)).EQ.'H')THEN
                        DX=COORD_COLLOCPOINTS(COLLOCPOINTS_CONNECTIVITY(J,K),1)-COORD_COLLOCPOINTS(CP_S1,1)
			            DY=COORD_COLLOCPOINTS(COLLOCPOINTS_CONNECTIVITY(J,K),2)-COORD_COLLOCPOINTS(CP_S1,2)
	                    DZ=COORD_COLLOCPOINTS(COLLOCPOINTS_CONNECTIVITY(J,K),3)-COORD_COLLOCPOINTS(CP_S1,3)
			            R=DSQRT(DX*DX+DY*DY+DZ*DZ)
			            IF(R.LE.1.E-12) THEN
				            CP_H1=COLLOCPOINTS_CONNECTIVITY(J,K)
				        ENDIF
                    ENDIF
                ENDDO
            ENDDO
!            
            E=EMP(ND(ELEMENT),1)
            Nu=EMP(ND(ELEMENT),2)
            CRACKTIP_COLLOCPOINTS(CONT)=COLLOCPOINTS_CONNECTIVITY(ELEMENT,LOCAL_NUMBER)            
!            
            NEN=ELEM_TYPE(ELEMENT)*ORDER_ELEM(ELEMENT)+(ELEM_TYPE(ELEMENT)-3)*(ORDER_ELEM(ELEMENT)-1)*POL_FAMILY(ELEMENT)
            ALLOCATE(VALUES(NEN,3))	
	        DO K=1,NEN
		        VALUES(K,1)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),1)
		        VALUES(K,2)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),2)
		        VALUES(K,3)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),3)
	        ENDDO 
	        SELECT CASE(LOCAL_NUMBER)
	        CASE(1)                                         
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ) 
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ) 
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                   
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ) 
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)     
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                                                                                
                ELSE
                    CALL SHAPE_FUNCTIONS(1,-0.8D0,-1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)  
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                      
                ENDIF  
            CASE(2)                                    
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)   
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                              
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ) 
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)    
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)                       
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                                                           
                ELSE
                    CALL SHAPE_FUNCTIONS(1,0.8D0,-1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)  
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                     
                ENDIF
            CASE(3)                                    
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ) 
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                      
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)        
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                      
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                                                                                        
                ELSE
                    CALL SHAPE_FUNCTIONS(1,1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ) 
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                      
                ENDIF
            CASE(4)                                                                             
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)    
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                              
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)         
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                            
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3)  
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                        
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)       
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                        
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ) 
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                                                                                                         
                ELSE
                    CALL SHAPE_FUNCTIONS(1,-0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S1,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S1,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S1,3) 
                    R1=DSQRT(DX*DX+DY*DY+DZ*DZ)  
                    CP_S2=COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)
                    DX=COORD_CRACKTIP(CONT,1)-COORD_COLLOCPOINTS(CP_S2,1)
                    DY=COORD_CRACKTIP(CONT,2)-COORD_COLLOCPOINTS(CP_S2,2)
                    DZ=COORD_CRACKTIP(CONT,3)-COORD_COLLOCPOINTS(CP_S2,3) 
                    R2=DSQRT(DX*DX+DY*DY+DZ*DZ)                        
                ENDIF             	        	        
	        ENDSELECT 
!            
            DO J=1,N_ELEM
                NEN=ELEM_TYPE(J)*ORDER_ELEM(J)+(ELEM_TYPE(J)-3)*(ORDER_ELEM(J)-1)*POL_FAMILY(J)
                DO K=1,NEN
                    IF(COLLOCPOINTS_CONNECTIVITY(J,K).EQ.CP_S2)THEN
                        ELEMENT=J
                        LOCAL_NUMBER=K                    
                    ENDIF
                    IF(DUAL_BEM(COLLOCPOINTS_CONNECTIVITY(J,K)).EQ.'H')THEN
                        DX=COORD_COLLOCPOINTS(COLLOCPOINTS_CONNECTIVITY(J,K),1)-COORD_COLLOCPOINTS(CP_S2,1)
			            DY=COORD_COLLOCPOINTS(COLLOCPOINTS_CONNECTIVITY(J,K),2)-COORD_COLLOCPOINTS(CP_S2,2)
	                    DZ=COORD_COLLOCPOINTS(COLLOCPOINTS_CONNECTIVITY(J,K),3)-COORD_COLLOCPOINTS(CP_S2,3)
			            R=DSQRT(DX*DX+DY*DY+DZ*DZ)
			            IF(R.LE.1.E-12) THEN
				            CP_H2=COLLOCPOINTS_CONNECTIVITY(J,K)
				        ENDIF
                    ENDIF
                ENDDO
            ENDDO	        
!
            COD1=-U(3*CP_S1-2)-U(3*CP_H1-2)          
            CSD1=-U(3*CP_S1-1)-U(3*CP_H1-1)        
            CTD1=-U(3*CP_S1)+U(3*CP_H1) 	
!
            KI1=(E/(4*(1-Nu**2)))*DSQRT(PI/(2*R1))*COD1
            KII1=(E/(4*(1-Nu**2)))*DSQRT(PI/(2*R1))*CSD1
            KIII1=(E/(4*(1+Nu)))*DSQRT(PI/(2*R1))*CTD1  
!
            COD2=-U(3*CP_S2-2)-U(3*CP_H2-2)          
            CSD2=-U(3*CP_S2-1)-U(3*CP_H2-1)        
            CTD2=-U(3*CP_S2)+U(3*CP_H2) 	
!
            KI2=(E/(4*(1-Nu**2)))*DSQRT(PI/(2*R2))*COD2
            KII2=(E/(4*(1-Nu**2)))*DSQRT(PI/(2*R2))*CSD2
            KIII2=(E/(4*(1+Nu)))*DSQRT(PI/(2*R2))*CTD2   
!
!            COD(CONT)=COD2 
!            CSD(CONT)=CSD2        
!            CTD(CONT)=CTD2
!!                              
!            KI(CONT)=KI2
!            KII(CONT)=KII2
!            KIII(CONT)=KIII2                   	        
!
            COD(CONT)=(COD1*(R1-R2)-R1*(COD1-COD2))/(R1-R2)        
            CSD(CONT)=(CSD1*(R1-R2)-R1*(CSD1-CSD2))/(R1-R2)          
            CTD(CONT)=(CTD1*(R1-R2)-R1*(CTD1-CTD2))/(R1-R2)
!                              
            KI(CONT)=(KI1*(R1-R2)-R1*(KI1-KI2))/(R1-R2)
            KII(CONT)=(KII1*(R1-R2)-R1*(KII1-KII2))/(R1-R2)
            KIII(CONT)=(KIII1*(R1-R2)-R1*(KIII1-KIII2))/(R1-R2)                    
! 	                                          
            DEALLOCATE(VALUES)                    
        ENDIF         
    ENDDO      
!
!------------------------------------------------------------------------------------------------------------------------------------------------------
!         WRITING THE RESULTS
!------------------------------------------------------------------------------------------------------------------------------------------------------            
!
	OPEN(90,file='LIXO',status='unknown')
		WRITE(90,500)'STRESS_INTENSITY_FACTORS',STEP,' ',TRIM(MINIMUM_MAXIMUM_LOAD),'.txt'
	CLOSE(90)
!	
	OPEN(90,file='LIXO',status='OLD')
		READ(90,500)NOME
	CLOSE(90, STATUS = 'DELETE')
	
	NOME=ADJUSTL(NOME)	
		
	OPEN(10,file='Output_data\'//NOME,status='unknown')
    
    WRITE(10,*)'CRACK MODE I'
	WRITE(10,*)'   CRACK TIP            X            Y            Z            COD               KI'
	DO I=1,N_CRACKTIPS
		WRITE(10,200)CRACKTIP_COLLOCPOINTS(I),COORD_CRACKTIP(I,1),COORD_CRACKTIP(I,2),COORD_CRACKTIP(I,3),COD(I),KI(I)
	ENDDO
    WRITE(10,*)
    WRITE(10,*)'CRACK MODE II'
	WRITE(10,*)'   CRACK TIP            X            Y            Z            CSD               KII'
	DO I=1,N_CRACKTIPS
		WRITE(10,200)CRACKTIP_COLLOCPOINTS(I),COORD_CRACKTIP(I,1),COORD_CRACKTIP(I,2),COORD_CRACKTIP(I,3),CSD(I),KII(I)
	ENDDO
    WRITE(10,*)
    WRITE(10,*)'CRACK MODE III'
	WRITE(10,*)'   CRACK TIP            X            Y            Z            CTD               KIII'
	DO I=1,N_CRACKTIPS
		WRITE(10,200)CRACKTIP_COLLOCPOINTS(I),COORD_CRACKTIP(I,1),COORD_CRACKTIP(I,2),COORD_CRACKTIP(I,3),CTD(I),KIII(I)
	ENDDO
!
	CLOSE(10) 	
!	
    200	FORMAT(4x,i5,4x,E13.6,4x,E13.6,4x,E13.6,4x,E13.6,4x,E13.6) 
    500 FORMAT(a,i4,a,a,a)    
!
    END SUBROUTINE DISPLACEMENT_EXTRAPOLATION_TECHNIQUE

