	SUBROUTINE DISPLACEMENT_FITTING_TECHNIQUE(STEP)
!	
    USE ISOPARAMETRIC_MESH
    USE MATERIALS
	USE CRACKS_DUAL_BEM
	USE SUB_REGIONS_INTERFACES
	USE ANALYSIS
	USE REMESHING
	USE PROPAGATION	  
	USE FATIGUE 
!
    IMPLICIT NONE
    INTEGER::STEP,I,J,K,NEN,ELEMENT,LOCAL_NUMBER,CONT
!    
    REAL*8::PI,R,THETA[ALLOCATABLE](:),UL[ALLOCATABLE](:),M[ALLOCATABLE](:,:),MT[ALLOCATABLE](:,:),MTM(6,6),MTMinv(6,6),Minv[ALLOCATABLE](:,:),SOLUCAO(6),E,Nu,Mu,KEPD,g1I,g2I,g1II,g2II,g3III,DIRECTION(3),ETAX(3),ETAY(3),R_S(3,3),R_H(3,3)
    REAL*8::VALUES[ALLOCATABLE](:,:),COEFFICIENTS[ALLOCATABLE](:,:),PHI[ALLOCATABLE](:),DPHI[ALLOCATABLE](:,:),D2PHI[ALLOCATABLE](:,:,:) 
!
    CHARACTER(40)::NOME         
!
! --------------------------------------------------------------------------------------------------------------------------------------------------
!   DEFINING THE CRACKTIP POINTS 
! --------------------------------------------------------------------------------------------------------------------------------------------------   
	PI=DACOS(-1.D0)
    N_CRACKTIPS=0      
    DO I=1,N_COLLOCPOINTS
        IF(DUAL_BEM(I).EQ."S")THEN            
            IF(CRACK_TIP(I).EQ.1.OR.CRACK_TIP(I).EQ.3)THEN
                N_CRACKTIPS=N_CRACKTIPS+1
            ENDIF
        ENDIF           
    ENDDO
  
    ALLOCATE(COORD_CRACKTIP(N_CRACKTIPS,3),KI(N_CRACKTIPS),KII(N_CRACKTIPS),KIII(N_CRACKTIPS),COD(N_CRACKTIPS),CSD(N_CRACKTIPS),CTD(N_CRACKTIPS),THETAP(N_CRACKTIPS),PHIP(N_CRACKTIPS),Keq(N_CRACKTIPS),Gmax(N_CRACKTIPS),CRACK_INCREMENT(N_CRACKTIPS),VERTICAL_INCREMENT(N_CRACKTIPS),CRACKTIP_COLLOCPOINTS(N_CRACKTIPS))   

    CONT=0 
    PI=DACOS(-1.D0)
    DO I=1,N_COLLOCPOINTS
        IF(CRACK_TIP(I).EQ.1.AND.DUAL_BEM(I).EQ."S")THEN
            CONT=CONT+1            
            DO J=1,N_ELEM
                NEN=ELEM_TYPE(J)*ORDER_ELEM(J)+(ELEM_TYPE(J)-3)*(ORDER_ELEM(J)-1)*POL_FAMILY(J)
                DO K=1,NEN
                    IF(COLLOCPOINTS_CONNECTIVITY(J,K).EQ.I)THEN
                        ELEMENT=J
                        LOCAL_NUMBER=K                    
                    ENDIF
                ENDDO
            ENDDO
!
            CRACKTIP_COLLOCPOINTS(CONT)=COLLOCPOINTS_CONNECTIVITY(ELEMENT,LOCAL_NUMBER)
!            
            NEN=ELEM_TYPE(ELEMENT)*ORDER_ELEM(ELEMENT)+(ELEM_TYPE(ELEMENT)-3)*(ORDER_ELEM(ELEMENT)-1)*POL_FAMILY(ELEMENT)
            ALLOCATE(VALUES(NEN,3))	
	        DO K=1,NEN
		        VALUES(K,1)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),1)
		        VALUES(K,2)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),2)
		        VALUES(K,3)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),3)
	        ENDDO 
	        SELECT CASE(LOCAL_NUMBER)
	        CASE(1)
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN                      	            
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                                              
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                               
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                   
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                      
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                         
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                         
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                          
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                                                                   
                ELSE
                    CALL SHAPE_FUNCTIONS(1,-0.8D0,-1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                       
                ENDIF  
            CASE(2)
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN                                    
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                                       
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                             
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                             
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                        
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                      
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                    
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                                                                                        
                ELSE
                    CALL SHAPE_FUNCTIONS(1,0.8D0,-1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                     
                ENDIF
            CASE(3)
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                                          
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                       
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                             
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                       
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                              
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                      
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                                                                  
                ELSE
                    CALL SHAPE_FUNCTIONS(1,1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                      
                ENDIF
            CASE(4)                                     
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                                               
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                              
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                    
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                      
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                    
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                      
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                                                                                     
                ELSE
                    CALL SHAPE_FUNCTIONS(1,-0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                      
                ENDIF             	        	        
	        ENDSELECT            	                                          
            DEALLOCATE(VALUES)  
!                              
        ELSE IF(CRACK_TIP(I).EQ.3.AND.DUAL_BEM(I).EQ."S")THEN
            CONT=CONT+1
!            
            DO J=1,N_ELEM
                NEN=ELEM_TYPE(J)*ORDER_ELEM(J)+(ELEM_TYPE(J)-3)*(ORDER_ELEM(J)-1)*POL_FAMILY(J)
                DO K=1,NEN
                    IF(COLLOCPOINTS_CONNECTIVITY(J,K).EQ.I)THEN
                        ELEMENT=J
                        LOCAL_NUMBER=K                    
                    ENDIF
                ENDDO
            ENDDO
!            
            CRACKTIP_COLLOCPOINTS(CONT)=COLLOCPOINTS_CONNECTIVITY(ELEMENT,LOCAL_NUMBER)            
!            
            NEN=ELEM_TYPE(ELEMENT)*ORDER_ELEM(ELEMENT)+(ELEM_TYPE(ELEMENT)-3)*(ORDER_ELEM(ELEMENT)-1)*POL_FAMILY(ELEMENT)
            ALLOCATE(VALUES(NEN,3))	
	        DO K=1,NEN
		        VALUES(K,1)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),1)
		        VALUES(K,2)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),2)
		        VALUES(K,3)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),3)
	        ENDDO 
	        SELECT CASE(LOCAL_NUMBER)
	        CASE(1)                                         
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                               
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                    
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                    
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                                                                                 
                ELSE
                    CALL SHAPE_FUNCTIONS(1,-0.8D0,-1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                      
                ENDIF  
            CASE(2)                                    
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                            
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                    
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                     
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                                                            
                ELSE
                    CALL SHAPE_FUNCTIONS(1,0.8D0,-1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                     
                ENDIF
            CASE(3)                                    
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                      
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                      
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                      
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                                                                                         
                ELSE
                    CALL SHAPE_FUNCTIONS(1,1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                     
                ENDIF
            CASE(4)                                                                             
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                            
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                           
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                        
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                        
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                                                                                          
                ELSE
                    CALL SHAPE_FUNCTIONS(1,-0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                        
                ENDIF             	        	        
	        ENDSELECT         	                                          
            DEALLOCATE(VALUES)                    
        ENDIF         
    ENDDO         
! --------------------------------------------------------------------------------------------------------------------------------------------------
!   DEFINING THE RADIAL INTERNAL POINTS 
! --------------------------------------------------------------------------------------------------------------------------------------------------       
    N_INTPOINTS=N_SITEXTRACTION_POINTS*N_CRACKTIPS
    ALLOCATE(COORD_INTPOINTS(N_INTPOINTS,3),NDI(N_INTPOINTS),UL(3*N_SITEXTRACTION_POINTS),M(3*N_SITEXTRACTION_POINTS,6),MT(6,3*N_SITEXTRACTION_POINTS),Minv(6,3*N_SITEXTRACTION_POINTS),THETA(N_SITEXTRACTION_POINTS))
    M=0.D0
    R=INTPOINTS_RADIUS  
!
    DO I=1,N_SITEXTRACTION_POINTS
        THETA(I)=-0.75D0*PI+(1.5D0*PI/(N_SITEXTRACTION_POINTS-1.D0))*(I-1)
    ENDDO
!    
    CONT=0 
    DO I=1,N_COLLOCPOINTS
        IF(DUAL_BEM(I).EQ."S")THEN
            IF(CRACK_TIP(I).EQ.1.OR.CRACK_TIP(I).EQ.3)THEN
                CONT=CONT+1
                DO J=1,N_ELEM
                    NEN=ELEM_TYPE(J)*ORDER_ELEM(J)+(ELEM_TYPE(J)-3)*(ORDER_ELEM(J)-1)*POL_FAMILY(J)
                    DO K=1,NEN
                        IF(COLLOCPOINTS_CONNECTIVITY(J,K).EQ.I)THEN
                            ELEMENT=J
                            LOCAL_NUMBER=K                    
                        ENDIF
                    ENDDO
                ENDDO  
     	        CALL LOCAL_COODINATE_SYSTEM(LOCAL_NUMBER,ELEMENT,R_S,R_H) 	
                ETAX(1)=R_S(1,1)
                ETAX(2)=R_S(1,2)
                ETAX(3)=R_S(1,3) 	
                ETAY(1)=R_S(2,1)
                ETAY(2)=R_S(2,2)
                ETAY(3)=R_S(2,3)
                DO J=1,N_SITEXTRACTION_POINTS
                    DIRECTION=COS(THETA(J))*ETAY+SIN(THETA(J))*ETAX
                    DIRECTION=DIRECTION/DSQRT(DIRECTION(1)**2+DIRECTION(2)**2+DIRECTION(3)**2)  	                 	        
                    COORD_INTPOINTS(N_SITEXTRACTION_POINTS*CONT-(N_SITEXTRACTION_POINTS-J),:)=COORD_CRACKTIP(CONT,:)+R*DIRECTION
                    NDI(N_SITEXTRACTION_POINTS*CONT-(N_SITEXTRACTION_POINTS-J))=ND(ELEMENT)                
                ENDDO                                                             
            ENDIF 
        ENDIF
    ENDDO
! --------------------------------------------------------------------------------------------------------------------------------------------------
!   COMPUTING THE INTERNAL DISPLACEMENTS
! --------------------------------------------------------------------------------------------------------------------------------------------------   
    CALL INTERNAL_DISPLACEMENTS           
! --------------------------------------------------------------------------------------------------------------------------------------------------
!   DISPLACEMENT FITTING TECHNIQUE: COMPUTING THE STRESS INTENSITY FACTORS KI, KII, KIII
! --------------------------------------------------------------------------------------------------------------------------------------------------   
    CONT=0 
    DO I=1,N_COLLOCPOINTS
        IF(DUAL_BEM(I).EQ."S")THEN
            IF(CRACK_TIP(I).EQ.1.OR.CRACK_TIP(I).EQ.3)THEN
                CONT=CONT+1
                DO J=1,N_ELEM
                    NEN=ELEM_TYPE(J)*ORDER_ELEM(J)+(ELEM_TYPE(J)-3)*(ORDER_ELEM(J)-1)*POL_FAMILY(J)
                    DO K=1,NEN
                        IF(COLLOCPOINTS_CONNECTIVITY(J,K).EQ.I)THEN
                            ELEMENT=J
                            LOCAL_NUMBER=K                    
                        ENDIF
                    ENDDO
                ENDDO
                
                E=EMP(ND(ELEMENT),1)
                Nu=EMP(ND(ELEMENT),2)
                Mu=E/(2*(1+Nu))
                KEPD=3-4*Nu
              
     	        CALL LOCAL_COODINATE_SYSTEM(LOCAL_NUMBER,ELEMENT,R_S,R_H)
     	        
     	        DO J=1,N_SITEXTRACTION_POINTS    	        
     	            UL(3*J-2)=R_S(1,1)*U_INT(3*(N_SITEXTRACTION_POINTS*CONT-N_SITEXTRACTION_POINTS+J)-2)+R_S(1,2)*U_INT(3*(N_SITEXTRACTION_POINTS*CONT-N_SITEXTRACTION_POINTS+J)-1)+R_S(1,3)*U_INT(3*(N_SITEXTRACTION_POINTS*CONT-N_SITEXTRACTION_POINTS+J)) 
     	            UL(3*J-1)=R_S(2,1)*U_INT(3*(N_SITEXTRACTION_POINTS*CONT-N_SITEXTRACTION_POINTS+J)-2)+R_S(2,2)*U_INT(3*(N_SITEXTRACTION_POINTS*CONT-N_SITEXTRACTION_POINTS+J)-1)+R_S(2,3)*U_INT(3*(N_SITEXTRACTION_POINTS*CONT-N_SITEXTRACTION_POINTS+J)) 
     	            UL(3*J)=R_S(3,1)*U_INT(3*(N_SITEXTRACTION_POINTS*CONT-N_SITEXTRACTION_POINTS+J)-2)+R_S(3,2)*U_INT(3*(N_SITEXTRACTION_POINTS*CONT-N_SITEXTRACTION_POINTS+J)-1)+R_S(3,3)*U_INT(3*(N_SITEXTRACTION_POINTS*CONT-N_SITEXTRACTION_POINTS+J))
     	            
     	            g1I=(KEPD-COS(THETA(J)))*COS(THETA(J)/2.D0)
     	            g2I=(KEPD-COS(THETA(J)))*SIN(THETA(J)/2.D0)
     	            g1II=(KEPD+2+COS(THETA(J)))*SIN(THETA(J)/2.D0)
     	            g2II=-(KEPD-2+COS(THETA(J)))*COS(THETA(J)/2.D0)
     	            g3III=4*SIN(THETA(J)/2.D0)
                    
                    M(3*J-2,1)=DSQRT(R)*g2I
                    M(3*J-2,2)=DSQRT(R)*g2II  
                    M(3*J-2,4)=R
                    
                    M(3*J-1,1)=DSQRT(R)*g1I
                    M(3*J-1,2)=DSQRT(R)*g1II  
                    M(3*J-1,5)=R
                    
                    M(3*J,3)=DSQRT(R)*g3III  
                    M(3*J,6)=R    	                    	        
     	        ENDDO
     	        
     	        MT=TRANSPOSE(M)
     	        MTM=MATMUL(MT,M)
     	        CALL DLINRG(6,MTM,6,MTMinv,6)
     	        Minv=MATMUL(MTMinv,MT)
     	        
     	        SOLUCAO=2*Mu*DSQRT(2*PI)*MATMUL(Minv,UL)
     	        
     	        KI(CONT)=SOLUCAO(1)
     	        KII(CONT)=SOLUCAO(2)
     	        KIII(CONT)=SOLUCAO(3)     	            	          	               	           	            	        
     	    ENDIF
        ENDIF
    ENDDO           
    DEALLOCATE(COORD_INTPOINTS,NDI,U_INT)
!------------------------------------------------------------------------------------------------------------------------------------------------------
!         WRITING THE RESULTS
!------------------------------------------------------------------------------------------------------------------------------------------------------            
!
	OPEN(90,file='LIXO',status='unknown')
		WRITE(90,500)'STRESS_INTENSITY_FACTORS',STEP,' ',TRIM(MINIMUM_MAXIMUM_LOAD),'.txt'
	CLOSE(90)
!	
	OPEN(90,file='LIXO',status='OLD')
		READ(90,500)NOME
	CLOSE(90, STATUS = 'DELETE')
	
	NOME=ADJUSTL(NOME)	
		
	OPEN(10,file='Output_data\'//NOME,status='unknown')
    
    WRITE(10,*)'CRACK MODE I'
	WRITE(10,*)'   CRACK TIP            X            Y            Z               KI'
	DO I=1,N_CRACKTIPS
		WRITE(10,200)CRACKTIP_COLLOCPOINTS(I),COORD_CRACKTIP(I,1),COORD_CRACKTIP(I,2),COORD_CRACKTIP(I,3),KI(I)
	ENDDO
    WRITE(10,*)
    WRITE(10,*)'CRACK MODE II'
	WRITE(10,*)'   CRACK TIP            X            Y            Z               KII'
	DO I=1,N_CRACKTIPS
		WRITE(10,200)CRACKTIP_COLLOCPOINTS(I),COORD_CRACKTIP(I,1),COORD_CRACKTIP(I,2),COORD_CRACKTIP(I,3),KII(I)
	ENDDO
    WRITE(10,*)
    WRITE(10,*)'CRACK MODE III'
	WRITE(10,*)'   CRACK TIP            X            Y            Z               KIII'
	DO I=1,N_CRACKTIPS
		WRITE(10,200)CRACKTIP_COLLOCPOINTS(I),COORD_CRACKTIP(I,1),COORD_CRACKTIP(I,2),COORD_CRACKTIP(I,3),KIII(I)
	ENDDO
!
	CLOSE(10)
!	
    200	FORMAT(4x,i5,4x,E13.6,4x,E13.6,4x,E13.6,4x,E13.6) 
    300	FORMAT(4x,i5,4x,E13.6,4x,E13.6,4x,E13.6)     
    500 FORMAT(a,i4,a,a,a)     
!
    END SUBROUTINE DISPLACEMENT_FITTING_TECHNIQUE

