!**********************************************************************!
!   FATIGUE_FRACTURE_3D: FATIGUE AND FRACTURE OF CRACKED MECHANICAL COMPONENTS        
!                                                               
!	UNIVERSITY OF SÃO PAULO                                            
!	SCHOOL OF ENGINEERING OF SÃO CARLOS                                
!   DEPARTMENT OF STRUCTURAL ENGINEERING                              
!	AVENIDA TRABALHADOR SAOCARLENSE, 400. SAO CARLOS-SP, BRAZIL.
!   POSTAL CODE 13.566-590. PHONE +(55)3373-8211. FAX+(55)3373-9482
!                                                                    
!   AUTHORS: 
!   ANTONIO RODRIGUES NETO
!   MATHEUS ROCHA (MATHEUSROCHA.BR95@GMAIL.COM)
!   SÉRGIO GUSTAVO FERREIRA CORDEIRO (SERGIO.CORDEIRO@USP.BR)	
!
!	THIS COMPUTATIONAL CODE WAS DEVELOPED TO INTEGRATE IGES GEOMETRICAL FILES WITH THE DUAL BOUNDARY ELEMENT METHOD  
!   FOR FATIGUE AND FRACTURE OF CRACKED MECHANICAL COMPONENTS                                                 
!
!**********************************************************************!
	PROGRAM	FATIGUE_FRACTURE_3D
	IMPLICIT NONE
!
	INTEGER::I,DATE_TIME_I(8),DATE_TIME_F(8),COMPUTATIONAL_WORK
!
    CHARACTER(8)::DATE
    CHARACTER(10)::TIME
    CHARACTER(5)::ZONE
!    
    CALL DATE_AND_TIME(DATE,TIME,ZONE,DATE_TIME_I)
!   
    WRITE(*,*) "INPUT_DATA"
    CALL INPUT_DATA
!
    CALL ANALYZES
!      	
	DO I=1,22
		WRITE(*,*)''
	ENDDO
!
	WRITE(*,*)''
	WRITE(*,*)'SOLUTION IS DONE'
	WRITE(*,*)''
!
    CALL DATE_AND_TIME(DATE,TIME,ZONE,DATE_TIME_F)  
!     
    COMPUTATIONAL_WORK=(DATE_TIME_F(3)-DATE_TIME_I(3))*24*60*60+(DATE_TIME_F(5)-DATE_TIME_I(5))*60*60+(DATE_TIME_F(6)-DATE_TIME_I(6))*60+(DATE_TIME_F(7)-DATE_TIME_I(7))+(DATE_TIME_F(8)-DATE_TIME_I(8))*0.001  
!
    OPEN(3,FILE='Output_data\Computational_time.txt',STATUS = 'UNKNOWN')
    WRITE(3,*)''
    IF (COMPUTATIONAL_WORK.LE.179) THEN
	    WRITE(3,100)'COMPUTATIONAL WORK, SECONDS',DFLOAT(COMPUTATIONAL_WORK)
    ELSE IF (COMPUTATIONAL_WORK.LE.4139) THEN
        WRITE(3,100)'COMPUTATIONAL WORK, MINUTES',COMPUTATIONAL_WORK/60.0
    ELSE IF (COMPUTATIONAL_WORK.LE.90000) THEN
        WRITE(3,100)'COMPUTATIONAL WORK, HOURS',COMPUTATIONAL_WORK/60.0/60.0
    ELSE
        WRITE(3,100)'COMPUTATIONAL WORK, DAYS',COMPUTATIONAL_WORK/60.0/60.0/24.0
    ENDIF
    WRITE(3,*)''
    
    CLOSE(3)
    
    WRITE(*,*)''
    IF (COMPUTATIONAL_WORK.LE.179) THEN
	    WRITE(*,100)'COMPUTATIONAL WORK, SECONDS',DFLOAT(COMPUTATIONAL_WORK)
    ELSE IF (COMPUTATIONAL_WORK.LE.4139) THEN
        WRITE(*,100)'COMPUTATIONAL WORK, MINUTES',COMPUTATIONAL_WORK/60.0
    ELSE IF (COMPUTATIONAL_WORK.LE.90000) THEN
        WRITE(*,100)'COMPUTATIONAL WORK, HOURS',COMPUTATIONAL_WORK/60.0/60.0
    ELSE
        WRITE(*,100)'COMPUTATIONAL WORK, DAYS',COMPUTATIONAL_WORK/60.0/60.0/24.0
    ENDIF
	READ(*,*)
    
    100 FORMAT(A,4x,F16.4)   
    
	END PROGRAM FATIGUE_FRACTURE_3D