    SUBROUTINE FIND_ENRICHED_SUPPS
!   IDENTIFYING ELEMENT CONTAINING CONCENTRATED SUPPORT AND CALCULATING ADIMENSIONAL PARAMETERS OF CONCENTRATED SUPPORT POINT
    USE ISOPARAMETRIC_MESH
	USE MATERIALS
	USE CRACKS_DUAL_BEM
	USE SUB_REGIONS_INTERFACES
	USE ANALYSIS
    USE XBEM_SUPPORT_VARIABLES
!   
    IMPLICIT NONE
!
    INTEGER::I,J,ELEM_NODE,CONT
    REAL*8::QSI_PNT(2)
! 
    ALLOCATE(ELEM_CON_SUPP(NUM_CON_SUPPS),QSI_CON_SUPP(NUM_CON_SUPPS,2),INT_DIR_CON_SUPPS(NUM_CON_SUPPS))
    DO I=1,NUM_CON_SUPPS
        ELEM_NODE=0
        CALL FIND_ELEMENT_WITH_PNT(COORDS_CON_SUPPS(I,:),ELEM_CON_SUPP(I),QSI_CON_SUPP(I,:))
!       DEFINING DIRECTION NUMBER OF CONCENTRATED SUPPORT
        IF(DIR_CON_SUPPS(I).EQ."X")THEN
            INT_DIR_CON_SUPPS(I)=1
        ELSEIF(DIR_CON_SUPPS(I).EQ."Y")THEN
            INT_DIR_CON_SUPPS(I)=2 
        ELSEIF(DIR_CON_SUPPS(I).EQ."Z")THEN
            INT_DIR_CON_SUPPS(I)=3
        ENDIF
    ENDDO
!
    OPEN(5,file='KSIS_CONC.txt',status='unknown')
    WRITE(5,*)'ELEM     KSI1        KSI2'
    DO I=1,NUM_CON_SUPPS
        WRITE(5,*)ELEM_CON_SUPP(I),QSI_CON_SUPP(I,1),QSI_CON_SUPP(I,2)
    ENDDO    
    CLOSE(5)
!
    ALLOCATE(ELEM_DIST_SUPP(NODES_DIST_SUPPS),QSI_DIST_SUPP(NODES_DIST_SUPPS,2))
    DO I=1,NODES_DIST_SUPPS_X
        ELEM_NODE=0
        CALL FIND_ELEMENT_WITH_PNT(COORDS_DIST_SUPPS_X(I,:),ELEM_DIST_SUPP(I),QSI_DIST_SUPP(I,:))
        VALUES_DIST_SUPPS(I)=VALUES_DIST_SUPPS_X(I)
    ENDDO
!
    CONT=NODES_DIST_SUPPS_X
    DO I=1,NODES_DIST_SUPPS_Y
        ELEM_NODE=0
        CALL FIND_ELEMENT_WITH_PNT(COORDS_DIST_SUPPS_Y(I,:),ELEM_DIST_SUPP(CONT+I),QSI_DIST_SUPP(CONT+I,:))
        VALUES_DIST_SUPPS(CONT+I)=VALUES_DIST_SUPPS_Y(I)
    ENDDO
!
    CONT=NODES_DIST_SUPPS_X+NODES_DIST_SUPPS_Y
    DO I=1,NODES_DIST_SUPPS_Z
        ELEM_NODE=0
        CALL FIND_ELEMENT_WITH_PNT(COORDS_DIST_SUPPS_Z(I,:),ELEM_DIST_SUPP(CONT+I),QSI_DIST_SUPP(CONT+I,:))
        VALUES_DIST_SUPPS(CONT+I)=VALUES_DIST_SUPPS_Z(I)
    ENDDO   
!
    
!
    !OPEN(5,file='KSIS_dist.txt',status='unknown')
    !WRITE(5,*)'ELEM     KSI1        KSI2'
    !DO I=1,NUM_DIST_SUPPS
    !    DO J=1,4
    !        WRITE(5,*)ELEM_DIST_SUPP(I,J),QSI_DIST_SUPP(I,J,1),QSI_DIST_SUPP(I,J,2)
    !    ENDDO
    !    WRITE(5,*)
    !ENDDO    
    !CLOSE(5)
!
    END SUBROUTINE