	SUBROUTINE GAUSS_POINTS(NG,QSIW_GAUSS)
!
	USE ANALYSIS
!
	IMPLICIT NONE 
!
	INTEGER::I,NG
    REAL(8)::QSIW_GAUSS(NG,2)
!    		 
	REAL*8::GI(NG),OME(NG)
! 
	GI=0.D0
	OME=0.D0
!	
    CALL DGQRUL (NG,1,0.D0,0.D0,0,GI,GI,OME)
!	  
	QSIW_GAUSS=0.D0
!
	DO I=1,NG
		QSIW_GAUSS(I,1)=GI(I)
		QSIW_GAUSS(I,2)=OME(I)
	ENDDO		
!				
	END SUBROUTINE