SUBROUTINE INTERFACE_HSL
!
  USE HSL_MA74_DOUBLE
  IMPLICIT NONE
  INTEGER, PARAMETER :: WP = KIND(1.0D0)
  TYPE(MA74_CONTROL) :: CONTROL
  TYPE(MA74_INFO) :: INFO
  INTEGER :: FLAG, I, J, LDAP, N, NB, P, Q, Q1
  REAL(WP), ALLOCATABLE :: AP(:,:), B(:), BLOCAL(:), X(:)
  INTEGER, ALLOCATABLE :: PPERM(:), QPERM(:)
  INTEGER, ALLOCATABLE :: PPERM1(:), QPERM1(:), IROW(:), JCOL(:)

! READ THE MATRIX ORDER AND NUMBER OF ELIMINATIONS FOR PARTIAL FACTORIZATION
  READ(*,*) N,P
  NB = MIN(P,100)
  LDAP = N

! ALLOCATE ARRAYS FOR PARTIAL FACTORIZATION
  ALLOCATE(AP(N,N), PPERM(N), QPERM(N))

! READ THE MATRIX BY COLUMNS
  DO J = 1,N
    READ(*,*) AP(1:N,J)
  END DO

! PERFORM PARTIAL FACTORIZATION
  CALL MA74_FACTOR(N,P,NB,AP,LDAP,Q,PPERM,QPERM,CONTROL,INFO)
  IF (INFO%FLAG /= 0) CALL TERMINATE("MA74_FACTOR")

! ALLOCATE ARRAYS FOR THE SOLVE
  ALLOCATE(B(N), X(N), BLOCAL(N))

! READ THE RIGHT-HAND SIDE
  READ(*,*) B(1:N)

  IF (Q > 0) THEN
! PERMUTE RIGHT-HAND SIDE B
    BLOCAL(1:N) = B(PPERM(1:N))

! PERFORM PARTIAL FORWARD SUBSTITUTION
    CALL MA74_SOLVEL1(N,Q,NB,AP,LDAP,BLOCAL,FLAG)
    IF (FLAG /= 0) CALL TERMINATE("MA74_SOLVEL1")

! PERMUTE BACK INTO B
    B(PPERM(1:N)) = BLOCAL(1:N)
  END IF

   IF (Q > 0) THEN
! LOAD PARTIAL SOLUTION INTO A LOCAL ARRAY BLOCAL
     BLOCAL(1:Q) = B(PPERM(1:Q))

! AND LOAD REQUIRED PART OF COMPUTED SOLUTION INTO BLOCAL
     BLOCAL(Q+1:N) = X(QPERM(Q+1:N))

! BACK SUBSTITUTION
     CALL MA74_SOLVEDU1(N,Q,NB,AP,LDAP,BLOCAL,FLAG)
     IF (FLAG /= 0) CALL TERMINATE("MA74_SOLVEDU1")
! COPY FROM BLOCAL INTO X
     X(QPERM(1:Q)) = BLOCAL(1:Q)
   END IF


  WRITE(*,'(A,8F10.3)') ' COMPUTED SOLUTION ',X(1:N)
  DEALLOCATE(AP, B, X, BLOCAL, PPERM, QPERM)
  IF (N > Q) DEALLOCATE(PPERM1, QPERM1, IROW, JCOL)

CONTAINS

  SUBROUTINE TERMINATE(NAME)
    CHARACTER(*) NAME
    WRITE(*,*) "STOPPING AFTER FAILURE IN ",NAME," WITH FLAG = ", FLAG
    STOP
  END SUBROUTINE TERMINATE
!
END