SUBROUTINE INTERFACE_OUTPUT(STEP,DU_TOTAL)
!
	USE ISOPARAMETRIC_MESH
	USE CRACKS_DUAL_BEM	
	USE ANALYSIS
	USE REMESHING
    USE SUB_REGIONS_INTERFACES
    USE COHESIVE
!
	IMPLICIT NONE 
!
	INTEGER::STEP,I,J,K,II,JJ,KK,L,NEN,C,N_CRACKED_ELEM
    INTEGER::INTERFACE_NODE,ELEM,LOCAL_NODE
!
    REAL*8::VALUES[ALLOCATABLE](:,:),ETA(3),VJC(3),DVJC(3,2),JC
	REAL*8::U_AUX(3),T_AUX(3),R_S(3,3),R_H(3,3),DX,DY,DZ,R,TN_DEG[ALLOCATABLE](:)
    REAL*8::ROTATION_MATRIX_S(3,3),ROTATION_MATRIX_H(3,3)
    REAL*8::T_INTERFACE[ALLOCATABLE](:),T_TANGENTIAL[ALLOCATABLE](:,:),DU_TOTAL(2*N_INTERFACE_POINTS),TOL_DU,F_T
!
    CHARACTER(40)::NOME		
    TOL_DU=1.D-8
    ALLOCATE(TN_DEG(N_INTERFACE_POINTS),T_INTERFACE(N_INTERFACE_POINTS),T_TANGENTIAL(N_INTERFACE_POINTS,2))
!
!------------------------------------------------------------------------------------------------------------------------------------------------------
!   CALCULATING PERCENTAGE OF NORMAL TRACTION AT NODE (CRIAR SUBROTINA DEPOIS)
!------------------------------------------------------------------------------------------------------------------------------------------------------
    DO I=1,N_INTERFACE_POINTS
        IF(NI_INTERFACE_NUMBER(I).GT.0)THEN
            ! COHESIVE PROPERTIES
            F_T=CMP(NI_INTERFACE_NUMBER(I),1)           
            INTERFACE_NODE=NI(I,1)
            ! ELEMENT THAT CONTAINS INTERFACE NODE
            DO J=1,N_ELEM
                NEN=ELEM_TYPE(J)*ORDER_ELEM(J)+(ELEM_TYPE(J)-3)*(ORDER_ELEM(J)-1)*POL_FAMILY(J)
                DO K=1,NEN
                    IF(COLLOCPOINTS_CONNECTIVITY(J,K).EQ.INTERFACE_NODE)THEN
                        ELEM=J
                        LOCAL_NODE=K
                    ENDIF
                ENDDO
            ENDDO
            NEN=ELEM_TYPE(ELEM)*ORDER_ELEM(ELEM)+(ELEM_TYPE(ELEM)-3)*(ORDER_ELEM(ELEM)-1)*POL_FAMILY(ELEM)
            ALLOCATE(VALUES(NEN,3))
            DO J=1,NEN
		        VALUES(J,1)=COORD_NODES(NODES_CONNECTIVITY(ELEM,J),1)
		        VALUES(J,2)=COORD_NODES(NODES_CONNECTIVITY(ELEM,J),2)
		        VALUES(J,3)=COORD_NODES(NODES_CONNECTIVITY(ELEM,J),3)
            ENDDO
	        CALL NORMAL_OUTWARD(NEN,VALUES,QSI(ELEM,LOCAL_NODE,1),QSI(ELEM,LOCAL_NODE,2),ETA,VJC,DVJC,JC)
            DEALLOCATE(VALUES)
            ! LOCAL ROTATION MATRIX
            CALL LOCAL_COODINATE_SYSTEM(LOCAL_NODE,ELEM,ROTATION_MATRIX_S,ROTATION_MATRIX_H)
    !
            T_INTERFACE(I)=T(3*INTERFACE_NODE-2)*ROTATION_MATRIX_S(1,1)+T(3*INTERFACE_NODE-1)*ROTATION_MATRIX_S(1,2)+T(3*INTERFACE_NODE)*ROTATION_MATRIX_S(1,3)
            T_TANGENTIAL(I,1)=T(3*INTERFACE_NODE-2)*ROTATION_MATRIX_S(2,1)+T(3*INTERFACE_NODE-1)*ROTATION_MATRIX_S(2,2)+T(3*INTERFACE_NODE)*ROTATION_MATRIX_S(2,3)
            T_TANGENTIAL(I,2)=T(3*INTERFACE_NODE-2)*ROTATION_MATRIX_S(3,1)+T(3*INTERFACE_NODE-1)*ROTATION_MATRIX_S(3,2)+T(3*INTERFACE_NODE)*ROTATION_MATRIX_S(3,3)
    !
            IF(DU_TOTAL(I).GT.TOL_DU)THEN
                TN_DEG(I)=T_INTERFACE(I)/F_T
            ELSE
                TN_DEG(I)=1.D0
            ENDIF
        ENDIF
    ENDDO
!------------------------------------------------------------------------------------------------------------------------------------------------------
!   WRITTING THE ACADVIEW FILE
!------------------------------------------------------------------------------------------------------------------------------------------------------
!
	OPEN(90,file='LIXO',status='unknown')
		WRITE(90,500)'INTERFACE_OUTPUT',STEP,'.ogl'
	CLOSE(90)
!	
	OPEN(90,file='LIXO',status='OLD')
		READ(90,500)NOME
	CLOSE(90, STATUS = 'DELETE')
	
	NOME=ADJUSTL(NOME)	
		
	OPEN(3,file='Output_data\'//NOME,status='unknown')
!
	WRITE(3,*)'Arquivo de pós-processamento'
	WRITE(3,*)
	WRITE(3,*)'Nº de nos     Nº de elementos     Nº de listas'
	WRITE(3,10)
	WRITE(3,100)N_INTERFACE_POINTS,N_ELEM_INT,3
    WRITE(3,*)
	WRITE(3,*)'coordx coordy coordz deslx delsy deslz'
	WRITE(3,10)
	DO I=1,N_INTERFACE_POINTS
	    WRITE(3,200)COORD_COLLOCPOINTS(NI(I,1),1),COORD_COLLOCPOINTS(NI(I,1),2),COORD_COLLOCPOINTS(NI(I,1),3),0.D0,0.D0,0.D0
	ENDDO
	WRITE(3,*)
	WRITE(3,*)'tpelem (1 - barra / 2 - triang / 3 - quad) grauaprox nó1 nó2...non'
	WRITE(3,10)
	DO I=1,N_ELEM_INT
	    IF(CRACKED_ELEM(I).EQ."UNCRACKED")THEN	
	        NEN=ELEM_TYPE(I)*ORDER_ELEM(I)+(ELEM_TYPE(I)-3)*(ORDER_ELEM(I)-1)*POL_FAMILY(I)
            SELECT CASE(NEN)
            CASE(3)
                WRITE(3,300)2,1,COLLOCPOINTS_CONNECTIVITY(I,3),COLLOCPOINTS_CONNECTIVITY(I,1),COLLOCPOINTS_CONNECTIVITY(I,2)
            CASE(6)
                WRITE(3,301)2,2,COLLOCPOINTS_CONNECTIVITY(I,3),COLLOCPOINTS_CONNECTIVITY(I,6),COLLOCPOINTS_CONNECTIVITY(I,1),COLLOCPOINTS_CONNECTIVITY(I,5),COLLOCPOINTS_CONNECTIVITY(I,4),COLLOCPOINTS_CONNECTIVITY(I,2)
            ! ONLY CHANGED CASE 4 DUE TO CODE LIMITATIONS REGARDING OTHER ELEMENT TYPES
            CASE(4)
                WRITE(3,302)3,1,INTERFACE_CONNECTIVITY(I,1),INTERFACE_CONNECTIVITY(I,2),INTERFACE_CONNECTIVITY(I,4),INTERFACE_CONNECTIVITY(I,3)
            CASE(8)
                WRITE(3,303)3,2,COLLOCPOINTS_CONNECTIVITY(I,1),COLLOCPOINTS_CONNECTIVITY(I,5),COLLOCPOINTS_CONNECTIVITY(I,2),COLLOCPOINTS_CONNECTIVITY(I,8),COLLOCPOINTS_CONNECTIVITY(I,6),COLLOCPOINTS_CONNECTIVITY(I,4),COLLOCPOINTS_CONNECTIVITY(I,7),COLLOCPOINTS_CONNECTIVITY(I,3)
            CASE(9)
                WRITE(3,304)3,2,COLLOCPOINTS_CONNECTIVITY(I,1),COLLOCPOINTS_CONNECTIVITY(I,5),COLLOCPOINTS_CONNECTIVITY(I,2),COLLOCPOINTS_CONNECTIVITY(I,8),COLLOCPOINTS_CONNECTIVITY(I,9),COLLOCPOINTS_CONNECTIVITY(I,6),COLLOCPOINTS_CONNECTIVITY(I,4),COLLOCPOINTS_CONNECTIVITY(I,7),COLLOCPOINTS_CONNECTIVITY(I,3)              
            ENDSELECT
        ENDIF
	ENDDO
	WRITE(3,*)
	WRITE(3,*)'Porcentagem de Força Normal degradada na interface'
	WRITE(3,10)
	WRITE(3,*)'TN_DEG'
	DO I=1,N_INTERFACE_POINTS
	    WRITE(3,400)0.D0,0.D0,0.D0,TN_DEG(I)   
    ENDDO
    WRITE(3,*)
	WRITE(3,*)'Força Normal na interface'
	WRITE(3,10)
	WRITE(3,*)'CHS_N'
	DO I=1,N_INTERFACE_POINTS
	    WRITE(3,400)0.D0,0.D0,0.D0,T_INTERFACE(I)   
    ENDDO
    WRITE(3,*)
    WRITE(3,*)'Força tangencial na interface'
	WRITE(3,10)
	WRITE(3,*)'TANGENTIAL_T'
	DO I=1,N_INTERFACE_POINTS
	    WRITE(3,400)0.D0,0.D0,0.D0,DSQRT(T_TANGENTIAL(I,1)*T_TANGENTIAL(I,1)+T_TANGENTIAL(I,2)*T_TANGENTIAL(I,2))
	ENDDO
!	
	CLOSE(3)
!
10  FORMAT(1h#)
100	FORMAT(2x,i5,12X,i5,12X,i5)
200	FORMAT(8x,F14.9,16x,F14.9,16x,F14.9,16x,F14.9,16X,F14.9,16x,F14.9)
300	FORMAT(8x,i1,7x,i1,7x,i5,7x,i5,7X,i5)
301	FORMAT(8x,i1,7x,i1,7x,i5,7x,i5,7x,i5,7x,i5,7x,i5,7x,i5)
302	FORMAT(8x,i1,7x,i1,7x,i5,7x,i5,7x,i5,7x,i5)
303	FORMAT(8x,i1,7x,i1,7x,i5,7x,i5,7x,i5,7x,i5,7x,i5,7x,i5,7x,i5,7x,i5)
304	FORMAT(8x,i1,7x,i1,7x,i5,7x,i5,7x,i5,7x,i5,7x,i5,7x,i5,7x,i5,7x,i5,7x,i5)
400	FORMAT(8x,E13.6,4x,E13.6,4x,E13.6,15x,E13.6)
500 FORMAT(a,i4,a)
		 
    END SUBROUTINE