!******************************************************************************************************************************
	MODULE NURBS_SURFACES
!	
	INTEGER::N_DOMAINS,N_SURFACES,N_CONTROLPOINTS,N_BF[ALLOCATABLE](:,:),POLYNOMIAL_ORDERS[ALLOCATABLE](:,:),N_GBF[ALLOCATABLE](:),SUBDIVISION_PD1[ALLOCATABLE](:),SUBDIVISION_PD2[ALLOCATABLE](:),CONTROLPOINTS_CONNECTIVITY[ALLOCATABLE](:,:),DOMAINS[ALLOCATABLE](:),SURFACE_INVERTION[ALLOCATABLE](:)     
!
	REAL*8::COORD_CONTROLPOINTS[ALLOCATABLE](:,:),KNOT_VECTORS[ALLOCATABLE](:,:,:),NODES[ALLOCATABLE](:,:,:)
!
    CHARACTER*30::SURFACE_TYPE[ALLOCATABLE](:),TRIMMED_SURFACE[ALLOCATABLE](:),DESCONT_TYPE[ALLOCATABLE](:)	         
!           
!
	END MODULE NURBS_SURFACES
!
!	N_DOMAINS = NUMBER OF DOMAIS (SUB-REGION TECHNIQUE)
!	N_SURFACES = NUMBER OF NURBS SURFACES THAT DESCRIBES THE GEOMETRY
!	N_CONTROLPOINTS = NUMBER OF CONTROL POINTS
!   N_BF = NUMBER OF UNIVARIATE BASIS FUNCTIONS IN A PARAMETRIC DIRECTION OF A GIVEN NURB (N_BF(patch,1)= n,N_BF(patch,2)= m)  
!	POLYNOMIAL_ORDERS = POLYNOMIAL ORDERS p AND q OF THE BASIS FUNCTIONS OF A NURB SURFACE (POLYNOMIAL_ORDERS(pach,1)= p, POLYNOMIAL_ORDERS(patch,2)= q)
!	N_GBF = NUMBER OF GLOBAL BIVARIATE BASES FUNCTIONS IN A GIVEN PATCH (N_GBF(patch))
!   SUBDIVISION_PD1/PD2 = VECTOR THAT CONTAINS THE NUMBER OF SUBDIVISIONS (N) FOR EACH PARAMETRIC DIRECTIONS (PD1 OR PD2) OF THE NURBS SURFACES
!   CONTROLPOINTS_CONECTIVITY = IT INDICATES THE CONTROL POINTS CONECTIVITY ON EACH NURB SURFACE: (CONNECTIVITY(PATCH,cp)=CP): cp = LOCAL CONTROL POINT NUMBER, CP = GLOBAL CONTROL POINT NUMBER  
!
!	COORD_CONTROLPOINTS = COORDINATES AND WEIGHTS (X,Y,Z,W) OF THE CONTROL POINTS
!   KNOTS_VECTORS = KNOTS VECTORS THAT DEFINE THE PATCHES (KNOTS_VECTORS(Patch,1,:)=QSI1 VALUES, KNOTS_VECTORS(Patch,2,:)=QSI2 VALUES)
!   NODES = PARAMETRIC COORDINATES (QSI1,QSI2) OF THE NODES 
!
!******************************************************************************************************************************
	MODULE TRIMMING_CURVES
!	
	INTEGER::N_TRIMMINGCURVES,N_PARAMETRICCONTROLPOINTS,N_BFCURVES[ALLOCATABLE](:),POLYNOMIAL_ORDER[ALLOCATABLE](:),SUBDIVISION[ALLOCATABLE](:),PARAMETRICCONTROLPOINTS_CONNECTIVITY[ALLOCATABLE](:,:),SURFACES[ALLOCATABLE](:)    
!
	REAL*8::COORD_PARAMETRICCONTROLPOINTS[ALLOCATABLE](:,:),KNOT_VECTOR[ALLOCATABLE](:,:)  
!
    CHARACTER*30::OPENED_CLOSED_CURVE[ALLOCATABLE](:),LAST_OPENED_CURVE[ALLOCATABLE](:)	                  
!
	END MODULE TRIMMING_CURVES
!

!
!******************************************************************************************************************************
	MODULE ISOPARAMETRIC_MESH
!	
	INTEGER::N_ELEM,N_NODES,N_COLLOCPOINTS,N_INTPOINTS,ELEM_TYPE[ALLOCATABLE](:),ORDER_ELEM[ALLOCATABLE](:),&
	POL_FAMILY[ALLOCATABLE](:),NODES_CONNECTIVITY[ALLOCATABLE](:,:),&
	COLLOCPOINTS_CONNECTIVITY[ALLOCATABLE](:,:),N_COLLOCPOINTS_SURFACES[ALLOCATABLE](:),N_ELEM_SURFACES[ALLOCATABLE](:),EDGE_DISCONTINUITY[ALLOCATABLE](:,:) 
!
	REAL*8::COORD_NODES[ALLOCATABLE](:,:),COORD_COLLOCPOINTS[ALLOCATABLE](:,:),&
    COORD_INTPOINTS[ALLOCATABLE](:,:),QSI[ALLOCATABLE](:,:,:)
!    
    CHARACTER*30::DISCONTINUOUS_COLLOCPOINTS[ALLOCATABLE](:),COMPUTER   	                
!
	END MODULE ISOPARAMETRIC_MESH		
!
!	N_ELEM = NUMBER OF ELEMENTS ON THE MESH
!	N_NODES = NUMBER OF NODES ON THE MESH
!	N_COLLOCPOINTS = NUMBER OF COLLOCATION POINTS ON THE MESH
!	N_INTPOINTS = NUMBER OF INTERNAL POINTS INSIDE THE DOMAIN
!	ELEM_TYPE = TYPE OF SURFACE ELEMENT: 3 (TRIANGULAR) OR  4 (QUADRILATERAL)
!   ORDER_ELEM = POLYNOMIAL DEGREE OF SHAPE FUNCTION ON EACH ELEMENT (1=LINEAR, 2=QUADRATIC)
!   POL_FAMILY = POLYNOMIAL FAMILY OF THE SHAPE FUNCTION ON EACH ELEMENT (0=SERENDIPITY, 1=LAGRANGIAN)
!   NODES_CONNECTIVITY = IT INDICATES THE CONECTIVITY OF THE NODES ON EACH ELEMENT: NODE = NODES_CONECTIVITY(ELEMENT,LOCAL NUMBER)
!   COLLOCPOINTS_CONNECTIVITY = IT INDICATES THE CONECTIVITY OF THE COLLOCATION POINTS ON EACH ELEMENT: COLLOCATION POINT = COLLOCPOINTS_CONECTIVITY(ELEMENT,LOCAL NUMBER)
!
!	COORD_NODES = NODAL COORDINATES (X,Y,Z) OF ALL NODES ON THE MESH
!   COORD_COLLOCPOINTS = COORDINATES (X,Y,Z) OF EACH COLLOCATION POINT
!   COORD_INTPOINTS = COORDINATES (X,Y,Z) OF EACH INTERNAL POINT
!   QSI = ADIMENSIONAL COORDINATES OF EACH COLLOCATION POINT ON EACH ELEMENT (ELEMENT NUMBER,LOCAL NODE,DIMENSIONLESS COORDINATE DIRECTION)
!
!   ELEMENT_CONTINUITY = CLASSIFY ELEMENTS INTO CONTINUOUS (C), DISCONTINUOUS (D) AND EDGE DISCONTINUOUS (ED123,ED12,ED124,ED24,ED234,ED34,ED134,ED13)
!   DISCONTINUOUS_COLLOCPOINTS = "DISCONTINUOUS" FOR COLLOCATION POINTS INSIDE THE ELEMENT, "CONTINUOUS" FOR COLLOCATION POINTS AT NODAL POSITIONS AND "EDGEDISCONTINUOUS" FOR COLLOCATION POINTS AT ELEMENTS EDGES 
!
!******************************************************************************************************************************
	MODULE MATERIALS
!
	REAL*8::EMP[ALLOCATABLE](:,:),FFMP[ALLOCATABLE](:,:)
!	
    END MODULE MATERIALS
!
!   EMP(ND,i) = MATRIX OF ELASTIC MATERIAL PROPERTIES: ND = DOMAIN NUMBER, i = ENGINEERING ELASTIC CONSTANTS 
!	EMP(ND,1) = YOUNG'S MODULUS (E)
!   EMP(ND,2) = POISSON'S RATIO (Nu)
!
!   FFMP(ND,i) = MATRIX OF FATIGUE AND FRACTURE MATERIAL PROPERTIES: ND = DOMAIN NUMBER, i = FRACTURE AND FATIGUE PROPRIETIES 
!	FFMP(ND,1) = FRACTURE TOUGHNESS (Kic)
!   FFMP(ND,2) = LINEAR PARIS LAW CONSTANT (C)
!   FFMP(ND,3) = EXPONENTIAL PARIS LAW CONSTANT (n) 
!
!
!******************************************************************************************************************************		
	MODULE CRACKS_DUAL_BEM
!
    CHARACTER*30::DUAL_BEM[ALLOCATABLE](:)
!
	INTEGER::N_CRACKS,N_CRACK_POINTS,NC[ALLOCATABLE](:,:),CRACK_TIP[ALLOCATABLE](:)  
!     
    REAL*8::COD[ALLOCATABLE](:),CSD[ALLOCATABLE](:),CTD[ALLOCATABLE](:),KI[ALLOCATABLE](:),KII[ALLOCATABLE](:),KIII[ALLOCATABLE](:),Keq[ALLOCATABLE](:)
!     
	END MODULE CRACKS_DUAL_BEM
!
!	DUAL_BEM = TYPE OF COLLOCATION POINT ("B" BOUNDARY, "S" SINGULAR CRACK SURFACE, "H" HYPER SINGULAR CRACK SURFACE) 
!
!	N_CRACKS = NUMBER OF CRACKS ON THE COMPONENT
!	N_CRACK_POINTS = NUMBER OF PAIR OF COLLOCATION POINTS AT THE CRACK SURFACES
!	NC = IT CONTAINS THE PAIR OF COLLOCATION POINTS AT THE CRACK SURFACES
!   CRACK_TIP = TYPE OF COLLOCATION POINT (0=NOT CRACK TIP, 1=CRACK TIP, 2=BOUNDARY CRACK TIP)
!
!******************************************************************************************************************************
	MODULE SUB_REGIONS_INTERFACES
!
	INTEGER::N_INTERFACE_POINTS,ND[ALLOCATABLE](:),NDI[ALLOCATABLE](:),NI[ALLOCATABLE](:,:),N_ELEM_INT,INTERFACE_CONNECTIVITY[ALLOCATABLE](:,:)  
!      
    END MODULE SUB_REGIONS_INTERFACES

!	N_INTERFACE_POINTS = NUMBER OF PAIR OF COLLOCATION POINTS AT THE INTERFACES
!	ND = NUMBER OF THE DOMAIN THAT CONTAINS A GIVEN ELEMENT
!	NDI = NUMBER OF THE DOMAIN THAT CONTAINS A GIVEN INTERNAL POINT 
!	NI = IT CONTAINS THE PAIR OF COLLOCATION POINTS AT THE INTERFACES
!   N_ELEM_INT = INTERFACE NUMBER OF ELEMENTS (DIVIDED BY 2)
!
!******************************************************************************************************************************
	MODULE ANALYSIS
!	
	CHARACTER*30::EQ_TYPE[ALLOCATABLE](:),INPUT_FILE,ANALYSIS_TYPE
!
	INTEGER::N_GAUSSPOINTS,N_LOAD_FASE,B_CONDITIONS[ALLOCATABLE](:)
!
	REAL*8::DIST,H[ALLOCATABLE](:,:),G[ALLOCATABLE](:,:),U[ALLOCATABLE](:),&
    T[ALLOCATABLE](:),HH[ALLOCATABLE](:,:),GG[ALLOCATABLE](:,:),U_INT[ALLOCATABLE](:),S_INT[ALLOCATABLE](:),&
    S_PRINCIPAL[ALLOCATABLE](:),TOL
!
	END MODULE ANALYSIS
!
!	EQ_TYPE = TYPE OF INTEGRAL EQUATION CHOSEN ON EACH COLLOCATION POINT. SINGULAR (S) OR HYPER SINGULAR (H)
!	INPUT_FILE = NAME OF THE MASTER INPUT_FILE (.txt)
!   ANALYSIS_TYPE = "BRITTLE_FRACTURE" OR "FATIGUE"
!
!	N_GAUSSPOINTS = NUMBER OF GAUSS POINTS TO INTEGRATE QUADRILATERAL ELEMENTS OR POLAR INTEGRATION IN TRIANGULAR ELEMENTS(SUBELEMENTS)
!	B_CONDITIONS = THIS VARIABLE INDICATES THAT DISPLACEMENT (O) OR TRACTION (1) IS PRESCRIBED ON EACH COLLOCATION POINT
!
!   DIST = DISTANCE (DIST=PERCENTAGE OF THE ELEMENT LENGHT) FOR EVALUATING COLLOCATION POINTS OUT OF THE BOUNDARY 
!	QSIW_GAUSS = MATRIX THAT CONTAINS THE ADIMENSIONAL GAUSS COORDINATES (-1 to 1) AND ITS HEIGHTS: QUADRILATERAL ELEMENTS
!   H = MATRIX THAT STORES THE KERNELS COMPUTED FROM THE KERNELS U*N OR n.SN
!   G = MATRIX THAT STORES THE KERNELS COMPUTED FROM THE KERNELS T*N OR n.D*N
!	T = TRACTIONS (TX,TY,TZ) AT EACH COLLOCATION POINT
!	U = DISPLACEMENTS (UX,UY,UZ) AT EACH COLLOCATION POINT
!   U_INT = DISPLACEMENT (UX,UY,UZ) AT EACH INTERNAL POINT
!   S_INT = STRESS COMPONENTES (SX,TXY,TXZ,SY,TYZ,SZ) AT EACH INTERNAL POINT
!   S_PRINCIPAL = PRINCIPAL STRESS (S1,S2,S3) AT EACH INTERNAL POINT
!
!******************************************************************************************************************************
    MODULE XBEM_FORCE_VARIABLES
!
    INTEGER:: NUM_CON_LOADS,NUM_DIST_LOADS,DIR_DIST_LOADS[ALLOCATABLE](:)
    REAL*8::COORDS_CON_LOADS[ALLOCATABLE](:,:),VALUES_CON_LOADS[ALLOCATABLE](:,:),&
    F_ENRICHED[ALLOCATABLE](:),F_ENRICHED_LOCAL(3),VALUES_DIST_LOADS[ALLOCATABLE](:,:,:)
    REAL*8::QSI_DIST[ALLOCATABLE](:,:,:)
    REAL*8::COORDS_DIST_LOADS[ALLOCATABLE](:,:,:)
!
    END MODULE XBEM_FORCE_VARIABLES
!
!   NUM_CON_LOADS = NUMBER OF CONCENTRATED LOADS APPLIED
!   COORDS_CON_LOADS = CONCENTRATED LOADS COORDINATES (X, Y, Z)
!   VALUES_CON_LOADS = CONCENTRATED LOADS VALUES (FX, FY, FZ)    
!
!******************************************************************************************************************************    
    MODULE XBEM_SUPPORT_VARIABLES
!
    CHARACTER*30::DIR_CON_SUPPS[ALLOCATABLE](:),DIR_DIST_SUPPS[ALLOCATABLE](:)
    INTEGER:: NUM_CON_SUPPS,INT_DIR_CON_SUPPS[ALLOCATABLE](:),&
    ELEM_CON_SUPP[ALLOCATABLE](:),NUM_DIST_SUPPS_X,NUM_DIST_SUPPS_Y,NUM_DIST_SUPPS_Z,&
    CONEC_DIST_SUPPS_X[ALLOCATABLE](:,:),CONEC_DIST_SUPPS_Y[ALLOCATABLE](:,:),CONEC_DIST_SUPPS_Z[ALLOCATABLE](:,:),&
    NODES_DIST_SUPPS_X,NODES_DIST_SUPPS_Y,NODES_DIST_SUPPS_Z,NODES_DIST_SUPPS,ELEM_DIST_SUPP[ALLOCATABLE](:),NUM_DIST_SUPPS
    REAL*8::COORDS_CON_SUPPS[ALLOCATABLE](:,:),VALUES_CON_SUPPS[ALLOCATABLE](:),&
    XBEM_SUPP_REACTIONS[ALLOCATABLE](:),QSI_CON_SUPP[ALLOCATABLE](:,:),XBEM_DIST_REACTIONS[ALLOCATABLE](:)
    REAL*8::AS_COL[ALLOCATABLE](:,:),AS_LIN[ALLOCATABLE](:,:)
    REAL*8::COORDS_DIST_SUPPS_X[ALLOCATABLE](:,:),COORDS_DIST_SUPPS_Y[ALLOCATABLE](:,:),COORDS_DIST_SUPPS_Z[ALLOCATABLE](:,:),&
    VALUES_DIST_SUPPS_X[ALLOCATABLE](:),VALUES_DIST_SUPPS_Y[ALLOCATABLE](:),VALUES_DIST_SUPPS_Z[ALLOCATABLE](:),&
    QSI_DIST_SUPP[ALLOCATABLE](:,:),VALUES_DIST_SUPPS[ALLOCATABLE](:)
!
!   ALLOCATE(ELEM_DIST_SUPP(NUM_DIST_SUPPS,4),QSI_DIST_SUPP(NUM_DIST_SUPPS,4,2),INT_DIR_DIST_SUPPS(NUM_DIST_SUPPS 
    END MODULE XBEM_SUPPORT_VARIABLES
!
!   DIR_CON_SUPPS = PRESCRIBED CONCENTRATED DISPLACEMENT DIRECTION (X, Y OR Z)
!   DIR_DIST_SUPPS = PRESCRIBED DISTRIBUTED DISPLACEMENT DIRECTION (X, Y OR Z)
!   NUM_CON_SUPPS = NUMBER OF CONCENTRATED SUPPORTS
!   NUM_DIST_SUPPS = NUMBER OF ENRICHED DISTRIBUTED SUPPORTS
!   INT_DIR_CON_SUPPS = NUMBER OF CONCENTRATED DISPLACEMENT DIRECTION (1 FOR X, 2 FOR Y AND 3 FOR Z)
!   INT_DIR_DIST_SUPPS = NUMBER OF DISTRIBUTED DISPLACEMENT DIRECTION (1 FOR X, 2 FOR Y AND 3 FOR Z)
!   COORDS_CON_SUPPS = CONCENTRATED SUPPORTS COORDINATES (X, Y, Z)
!   COORDS_DIST_SUPPS = DISTRIBUTED SUPPORT COORDINATES (X, Y, Z)
!   VALUES_CON_SUPPS = PRESCRIBED CONCENTRATED SUPPORTS DISPLACEMENTS (DIR, U_PRESC)
!   VALUES_DIST_SUPPS = PRESCRIBED DISTRIBUTED SUPPORTS DISPLACEMENTS (DIR, U_PRESC)
!   XBEM_SUPP_REACTIONS = VECTOR THAT CONTAINS REACTION VALUES OF XBEM SUPPORTS
!   QSI_CON_SUPP = CONCENTRATED SUPPORT ADIMENSIONAL COORDINATES IN ELEMENT
!   AS_COL = MATRIX WITH SUPPORT ENRICHMENT INFLUENCE COLUMNS 
!   AS_LIN = MATRIX WITH SUPPORT ENRICHMENT INFLUENCE LINES
!
!******************************************************************************************************************************   
    MODULE XBEM_CRACKFRONT_VARIABLES
!
    INTEGER::ALIGN_ELEM_S_NODE[ALLOCATABLE](:,:),ALIGN_ELEM_H_NODE[ALLOCATABLE](:,:),CRACK_TIP_PAIR[ALLOCATABLE](:,:),&
    N_ALIGNMENT_NODES,ENRICHED_ELEMS[ALLOCATABLE](:,:),N_K,N_ENRICHED_ELEMS
!
    REAL*8::ALIGN_ELEM_S_QSI[ALLOCATABLE](:,:),ALIGN_ELEM_H_QSI[ALLOCATABLE](:,:),CT_PAIR_QSI[ALLOCATABLE](:)
!
    END MODULE XBEM_CRACKFRONT_VARIABLES
!
!   N_ALIGNMENT_NODES = NUMBER OF ALIGNMENT NODES OF ALIGNMENT ELEMENT
!   ALIGN_ELEM_X_NODE(I,J): STORES NODE
!   ALIGN_ELEM_S_QSI
!   X DEFINES IF ALIGNMENT ELEMENT IS ASSOCIATED TO DISPL. EQN. OR TRACTION EQN.
!   CRACK_TIP_PAIR=PAIR OF CRACK TIPS IN CRACK FRONT, USED TO GENERATE K INTERPOLATION ELEMENT
!   CRACK_TIP_PAIR(I,1)=ELEMENT THAT CONTAIS CRACK FRONT
!   CRACK_TIP_PAIR(I,2)=1 IF QSI1 OF EACH NODE IS EQUAL, 2 IF QSI2 OF EACH NODE IS EQUAL
!   CRACK_TIP_PAIR(I,3...N)=NODES OF INTERPOLATION ELEMENT
!   CT_PAIR_QSI(I)=EQUAL QSI OF BOTH CRACK TIP POINTS
!   ENRICHED_ELEMS(I,1)=NUMBER OF ENRICHED ELEM
!   ENRICHED_ELEMS(I,2...,N)=CRACK TIP ASSOCIATED  
!   N_ENRICHED_ELEMS=NUMBER OF ENRICHED ELEMENTS IN EACH CRACK TIP PAIR
!
!******************************************************************************************************************************     
    MODULE REMESHING
!
	INTEGER::N_ADDELEM,N_ADDNODES,N_ADDCOLLOCPOINTS,CRACKED_EDGES[ALLOCATABLE](:,:),NEW_ELEMENTS[ALLOCATABLE](:,:)
!
    REAL*8::COORD_INTERCEPTPOINTS[ALLOCATABLE](:,:,:),COORD_EXTRAINTERCEPTPOINTS[ALLOCATABLE](:,:),COORD_BOUNDARYCRACKTIP[ALLOCATABLE](:,:),COORD_BOUNDARYCRACKTIPSTOP[ALLOCATABLE](:,:,:)
!    
    CHARACTER*30::CRACKED_ELEM[ALLOCATABLE](:),CHANGEABLE_ELEM[ALLOCATABLE](:),CHANGEABLE_COLLOCPOINTS[ALLOCATABLE](:)	     
!      
	END MODULE REMESHING

!	N_ADDELEM = NUMBER OF ADDITIONAL ELEMENTS DUE TO EDGE CRACK REMESHING	
!	N_ADDNODES = NUMBER OF ADDITIONAL NODES DUE TO EDGE CRACK REMESHING
!	N_ADDCOLLOCPOINTS = NUMBER OF ADDITIONAL COLLOCCATION POINTS DUE TO EDGE CRACK REMESHING
!   CRACKED_EDGES(N_ELEM,2) = INDICATE THE TWO CUTED EDGES IN THE CRACKED BOUNDARY ELEMENTS
!   COORD_INTERCEPTPOINTS=COORDINATES (X,Y,Z) OF EACH EDGE INTERCEPT POINT
!   COORD_BOUNDARYCRACKTIP(ELEM,3)=COORDINATES (X,Y,Z) OF THE BOUNDARY CRACK TIP AT THE ELEMENT ELEM
!	CRACKED_ELEM(N_ELEM) = "CRACKED" FOR ELEMENTS WITH TWO EDGES INTERCEPTED BY THE CRACK, "CRACKTIP" FOR ELEMENTS WITH ONE EDGES INTERCEPTED BY THE CRACK AND "UNCRACKED" OTHERWISE  
!
!******************************************************************************************************************************
	MODULE PROPAGATION
!
	INTEGER::N_STEPS,N_CRACKTIPS,N_CRACKTIPELEMENTS,N_CRACKTIPNODES,N_CRACKTIPCOLLOCPOINTS,N_SITEXTRACTION_POINTS,CRACKTIP_COLLOCPOINTS[ALLOCATABLE](:)
!
    REAL*8::COORD_CRACKTIP[ALLOCATABLE](:,:),CRACK_INCREMENT[ALLOCATABLE](:),VERTICAL_INCREMENT[ALLOCATABLE](:),Keqmax,MAX_CRACKINCREMENT,Gmax[ALLOCATABLE](:),THETAP[ALLOCATABLE](:),PHIP[ALLOCATABLE](:),INTPOINTS_RADIUS
!
    CHARACTER*30::SITEXTRACTION_METHOD,PROPAGATION_CRITERIA
!
    LOGICAL::PROPAGATE        
!      
	END MODULE PROPAGATION
!
!******************************************************************************************************************************
	MODULE FATIGUE
! 
    REAL*8::NCICLESi,NCICLES,DNCICLES,INITIAL_CRACKSIZE,CRACKSIZE,LOAD_RATIO,DKi,DKf,DKTH
    CHARACTER*30::MINIMUM_MAXIMUM_LOAD	      
!      
    END MODULE FATIGUE	
!
!******************************************************************************************************************************
    MODULE COHESIVE
! 
    CHARACTER*30::COHESIVE_OPERATOR
    CHARACTER*30::CM_TYPE[ALLOCATABLE](:)
!
    INTEGER::NUMBER_INTERFACES,ND_INT[ALLOCATABLE](:,:),NI_INTERFACE_NUMBER[ALLOCATABLE](:)
    INTEGER::CHS_B_CONDITIONS[ALLOCATABLE](:),N_COHESIVE_INCREMENTS,N_CHS_INTERFACE_POINTS,CHS_INT[ALLOCATABLE](:,:)
    INTEGER::TANGENT_BILINEAR[ALLOCATABLE](:),POS_CHS[ALLOCATABLE](:,:)
    INTEGER::N_CHS_INTERFACE_OUTPUT
    REAL*8::CHS_T[ALLOCATABLE](:),CHS_U[ALLOCATABLE](:),CHS_INV_A[ALLOCATABLE](:,:),CHS_B[ALLOCATABLE](:,:)
    REAL*8::H_R[ALLOCATABLE](:,:),G_R[ALLOCATABLE](:,:),CHS_COD[ALLOCATABLE](:),DELTA_P_EXC[ALLOCATABLE](:)
    REAL*8::IPVT_INV_A[ALLOCATABLE](:)
    REAL*8::ROTATION_INTERFACE_S[ALLOCATABLE](:,:,:),ROTATION_INTERFACE_H[ALLOCATABLE](:,:,:)
    REAL*8::CMP[ALLOCATABLE](:,:)
    REAL*8::TOL_F_EXC
!      
    END MODULE COHESIVE	
!    
!   NUMBER_INTERFACES: NUMBER OF PRESCRIBED INTERFACES
!   CM_TYPE(i) = TYPE OF COHESIVE LAW APPLIED (NONE,LINEAR,BILINEAR,EXPONENTIAL)
!   CMP(NUMBER_INTERFACE,J) = COHESIVE LAW PARAMETER J
!   GENERAL: J = 1: F_T, J = 2: CRITICAL OPENING, J = 3:FRACTURE ENERGY       
!   CHS_B_CONDITIONS = FLAG OF BOUNDARY CONDITIONS IN COHESIVE PROBLEM (0 IS DISPLACEMENT AND 1 IS TRACTION)
!   NI_INTERFACE_NUMBER(I) = NUMBER OF INTERFACE ASSOCIATED TO INTERFACE POINTS AT I POSITION IN NI
!   N_COHESIVE_INCREMENTS = NUMBER OF INCREMENTS IN COHESIVE ANALYSIS
!   N_CHS_INTERFACE_POINTS = NUMBER OF COHESIVE INTERFACE POINTS IN ITERATIVE ANALYSIS
!   N_CHS_INTERFACE_OUTPUT = NUMBER OF COHESIVE INTERFACE POINTS TO INTERFACE_OUTPUT
!   CHS_T = TRACTION BOUNDARY CONDITIONS OF COHESIVE ANALYSIS
!   CHS_U = DISPLACEMENT BOUNDARY CONDITIONS OF COHESIVE ANALYSIS
!   CHS_INV_A = INVERSE OF A MATRIX
!   CHS_INT = MATRIX WITH NODES AT COHESIVE ZONE (TANGENT OPERATOR)
!   CHS_COD = COHESIVE ZONE COD (CRACK OPENING DISPLACEMENTS)
!   DELTA_P_EXC = EXCEDENT NORMAL TRACTION THAT NEEDS TO BE REAPPLIED 
!   IPVT_INV_A = PIVOT VECTOR OF INV_A (FOR DLFTRG)
!   TANGENT_BILINEAR = VECTOR WITH BILINEAR TANGENT THAT WILL BE USED
!   ROTATION_INTERFACE_S = 3-DIMENSIONAL MATRIX WITH ROTATION MATRIX S OF (:,:,POS) INTERFACE POINT
!   ROTATION_INTERFACE_H = 3-DIMENSIONAL MATRIX WITH ROTATION MATRIX H OF (:,:,POS) INTERFACE POINT   
MODULE REINFORCEMENTS
    
    USE LAPACK95
    !DEC$ OBJCOMMENT LIB:'mkl_lapack95_lp64.lib'
    
    LOGICAL::VISCO_ANALYSIS_REINF,EP_ANALYSIS_REINF,SLIP_REINF
!
    CHARACTER*30::EXISTANCE_REINFORCEMENTS,FILE_REINFORCEMENTS,REINFORCEMENTS_METHOD,REINFORCEMENTS_ELASTOPLASTIC,NODE_HIST,&
        REINFORCEMENTS_SLIP,SLIP_LAW
!
    INTEGER::N_NOS_MEF,N_ELEMENTOS_MEF,TOTAL_ELEM_NODES_MEF,MAXORDER_MEF,N_INTERFACE_MEF,INPUT_INT_NODES,N_PASSOS,N_NODE_HIST,&
        N_NODAL_FORCES
    
    INTEGER,DIMENSION(:),ALLOCATABLE::ORDEM_MEF,ND_MEF,KODENODUPLO_MEF,N_INT_P_MEF,TIME_MODEL_REINF,NDI_INPUT,IPIV_A_GLOBAL_EP,&
        IPIV_A_GLOBAL_SLIP_F,IPIV_A_GLOBAL_SLIP_S,NI_SLIP_MEF,NI_PLAST_MEF
    
    INTEGER,DIMENSION(:,:),ALLOCATABLE::CONECTI_MEF,NI_MEF,NODAL_FORCES_PLACE
                
    REAL*8,DIMENSION(:),ALLOCATABLE::U_MEF,P_MEF,E_NORMAL_NOD,U_ANTERIOR_MEF,P_ANTERIOR_MEF,U_INT_INPUT,U_MEF_ACUM,U_ACUM_PL,P_MEF_ACUM,P_ACUM_PL,&
        F_DES_ANT,F_DES,F_ALVO,F_ACUM,P_MEF_AT,PL_STRAIN_NOD,SLIP_PARAMETERS,SLIP_MEF,S_ACUM,P_MEF_ACUM_LOCAL,NODAL_FORCES_VALUE,F_APP_DISP,F_APP_DISP_ACUM,&
        E_NORMAL_NOD_EL,E_NORMAL_NOD_VISCOSA
    
    REAL*8,DIMENSION(:,:),POINTER::KGLOBAL,GGLOBAL,G_CF,G_FF
    
    REAL*8,DIMENSION(:,:),ALLOCATABLE,TARGET::A_GLOBAL_ELASTIC
    
    REAL*8,DIMENSION(:,:),ALLOCATABLE::E_NORMAL,H_FC,G_FC,COORDPCOLOC_MEF,MP_MEF,QSI_MEF,COORDNOS_MEF,COORDINT_NOD_INPUT,MP_MEF_VISCO,&
        MP_EP_MEF,SIGMA_NOD,SIGMA_INTP_CONECT,SIGMA_INTP,LAMBDA,LAMBDA_CONECT,GRAND_ACUM_NOD,DEF_PL_NOD,DEF_INTP,D_SIGMA_INTP_CONECT,&
        D_SIGMA_INTP,D_DEF_PL_INTP_CONECT,D_DEF_PL_INTP,D_DEF_INTP,CARGA,ALFA,ALFA_CONECT,D_DEF_INTP_CONECT,B_GLOBAL_EP,A_GLOBAL_EP_LU,&
        KGLOBAL_SLIP,A_GLOBAL_SLIP_F,A_GLOBAL_SLIP_F_LU,B_GLOBAL_SLIP,A_GLOBAL_SLIP_S,A_GLOBAL_SLIP_S_LU,B_GLOBAL_SLIP_S,B_GLOBAL_EP_D,&
        B_CONC_F,KGLOBAL_NEW,GGLOBAL_NEW,B_GLOBAL_SLIP_F,E_NORMAL_EL,E_NORMAL_VISCOSA,E_NORMAL_ANTERIOR,E_NORMAL_EL_ANTERIOR
    
    REAL*8,DIMENSION(:,:,:),ALLOCATABLE::KKGLOBAL,GGGLOBAL,K_CONECT,G_CONECT
        
    REAL*8::EP_TOL,SLIP_TOL
    
    REAL*8,PARAMETER::TOLER=1.0D-13,INF_FIBRA=1.0D+10
    

END MODULE REINFORCEMENTS
!
!     INPUT_INT_NODES: NUMBER OS INTERNAL POINTS GIVEN BY USER
!     COORDINT_NOD_INPUT(I,J): COORDINATES X,Y,Z (J=1,2,3) OF EACH INTERNAL POINT I GIVEN BY USER
!     NDI_INPUT(I): GIVES THE DOMAIN OF THE INTERNAL POINT I GIVEN BY USER
!     U_INT_INPUT(I): SAVES THE X,Y,Z DISPLACEMENTS OF EACH INTERNAL POINT I GIVEN BY USER IN THIS ORDER: 3*I-3=X, 3*I-1=Y, 3*I=Z
!     N_NOS_MEF: NUMBER OF NODES OF THE FEM ELEMENTS
!     N_ELEMENTOS_MEF: NUMBER OF ELEMENTOS OF THE FEM ELEMENTS 
!     CONECTI_MEF(I,J): GLOBAL NUMBER OF THE NODES J THAT BELONG TO EACH ELEMENT I
!     ORDEM_MEF(I): ORDER OF SHAPE FUNCTIONS THAT APPROXIMATE DISPLACEMENTS AND TRACTIONS FOR EACH REINFORCEMENT ELEMNT I  
!     ND_MEF(I): DOMAIN IN WHICH EACH REINFORCEMENT ELEMENT I BELONG
!     KODENODUPLO_MEF(I): THIS VARIABLE INDICATES THE NODE I IS EITHER CONTINUOS OR DISCONTINUOUS. IF CONTINUOUS IT IS 0, IF DISCONTINUOUS IT IS 1
!     N_INT_P_MEF(I): VECTOR THAT CONTAINS THE NUMBER OF INTEGRATION POINTS FOR EACH ELEMENT I
!     TOTAL_ELEM_NODES_MEF: TOTAL NUMEBER OF NODES INSIDE ALL REINFORCEMENT ELEMENTS (sum N_ELEM*ORDER)
!     MAXORDER_MEF: VALUE OF MAXIMUM ORDER OF ALL REINFORCEMENT ELEMENTS IN THE MESH
!     COORDNOS_MEF(I,J): NODES COORDINATES X=NODE AND Y=DIRECTION FOR REINFORCEMENT MESH
!     QSI_MEF(I,J): ADIMENSIONAL COORDINATES QSI OF EACH FE NODE WHERE I=ELEMENT AND I=LOCAL NODE INSIDE ELEMENT I
!     MP_MEF(I,J): MATRIZ THAT CONTAINS THE YOUNGS MODULUS AND CROSS SECTION AREA OF EACH REINFORCEMENT ELEMENT I. WHERE J=1 IS YOUNG AND J=2 IS AREA
!     COORDPCOLOC_MEF(I,J):COORDINATES FOR ALL COLOCATION NODES OF REINFORC.ELEMENTS WHERE X=ELEMENT AND Y=DIRECTION
!     EXISTANCE_REINFORCEMENTS:VARIABLE THAT INDICATES EITHER THE PRESENCE OR ABSENCE OF REINFORCEMENTS
!     FILE_REINFORCEMENTS:INPUT FILE NAME
!     U_MEF(I): DISPLACEMENTS VALUES AT EACH REINFORC. MESH NODE WHERE 3*I=UZ AND 3*I-1=UY AND 3*I-2=UX
!     P_MEF(I): TRACTIONS VALUES AT EACH REINFORC. MESH NODE WHERE 3*I=PZ AND 3*I-1=PY AND 3*I-2=PX
!     REINFORCEMENTS_METHOD: CONTAINS THE METHOD TO DESCRIBE REINFORC. ELEMENTS (FEM OR 1DBEM)
!     KGLOBAL and GGLOBAL: MATRIXES OF THE FEM/1DBEM GLOBAL FOR THE FE
!     K_KGLOBAL and GG_GLOBAL: MATRIXES OF THE FEM/1DBEM GLOBAL FOR THE FE VISCOELASTIC ANALYSIS (MULTIPLIES P_ANTERIOR_MEF E U_ANTERIOR_MEF)
!     KKGLOBAL(K,I,J): MATRIX THAT CONTAINS THE LOCAL STIFFNESS MATRIXES(I,J) OF EACH REINFORCEMENT ELEMENT K
!     GGGLOBAL(K,I,J): LUMPING MATRIX(I,J) FOR EACH REINFORCEMENT ELEMENT K
!     N_INTERFACE_MEF: NUMBER OF CROSSING BETWEEN REINFORCEMENTS AND MEC INTERFACES
!     NI_MEF(I,J): MATRIX THAT CONTAINS EACH PAIR OF MEF NODES J (NODE 1 AND 2) FROM EACH CROSSING I
!     K_CONECT AND G_CONECT (I,J,K): MATRIXES(J,K) OF EACH CONNECTION ELEMENT I FOR EACH CROSSING
!     MP_EP_MEF(I,J): MATRIZ THAT CONTAINS THE SIGMMA Y STRESS (J=1), HARDENING MODULUS (J=2) AND ELASTOPLASTIC MODULOS (J=3) FOR EACH REINF ELEMENT I
!     N_PASSOS: NUMBER OF LOAD STEPS FOR ELASTOPLASTIC ANALYSIS 
!     EP_TOL: TOLERANCE FOR NEWTON-RAPHSON PROCESS WHEN THE REINFORCEMENT IS ELASTOPLASTIC
!     H_FC: MATRIX FROM COUPLING FORMULATION (3*N_NOS_MEF,3*N_NOS_BOUNDARY)
!     G_FC: MATRIX FROM COUPLING FORMULATION (3*N_NOS_MEF,3*N_NOS_BOUNDARY)
!     HH_FC: MATRIX FROM COUPLING FORMULATION (3*N_NOS_MEF,3*N_NOS_BOUNDARY) WITH VISCOELASTIC MEDIA
!     GG_FC: MATRIX FROM COUPLING FORMULATION (3*N_NOS_MEF,3*N_NOS_BOUNDARY) WITH VISCOELASTIC MEDIA
!     G_CF: MATRIX FROM COUPLING FORMULATION (3*N_NOS_MEF,3*N_NOS_BOUNDARY)
!     GG_CF: MATRIX FROM COUPLING FORMULATION (3*N_NOS_MEF,3*N_NOS_BOUNDARY) WITH VISCOELASTIC MEDIA
!     E_NORMAL(I,J): NORMAL EFFORT AT EACH LOCAL NODE (J) OF EACH REINFORCEMENT ELEMENT (I) 
!     E_NORMAL_NOD(I): VALUE OF NORMAL EFFORT AT EACH GLOBAL NODE (I) OF REINFORCEMENT'S MESH (MEAN VALUE OF ELEMENTS THAT THIS NODE BELONGS)
!     B_GLOBAL_FIX: MATRIX THAT CONTAIS THE VALUES OF BGLOBAL THAT DOES NOT CHANGE IN THE ELASTOPLASTIC PROCESS (SUBROUTINE REINF_SOLVER_PLAST)
!     A_GLOBAL_EP_LU: MATRIX THAT CONTAIS THE LU FACTORIZATION OF AGLOBAL MATRIX TO THENEXT ITERATIONS (ELASTOPLASTICITY)
!     A_GLOBAL_EP_IPIV: IPIV INFORMATION OF THE A_GLOBAL_LU MATRIX
!     SIGMA_NOD: MATRIZ THAT CONTAINS THE VALUE OF NORMAL STRESS IN THE NODAL POINTS OF EACH FINITE ELEMENT (FOR ELASTOPLASTIC ANALYSIS)
!     DEF_PL_NOD: MATRIX THAT CONTAINS THE VALUE OF PLASTIC DEFORMATION IN THE NODAL POINTS OF EACH FINITE ELEMENT (FOR ELASTOPLASTIC ANALYSIS)
!     F_DES: VECTOR THAT CONTAINS THE DESEQUILIBRED FORCES (DUE TO NEWTON-RAPHSON PROCESSO FOR ELASTOPLASTICITY)
!     F_DES_ANT: VECTOR THAT CONTAINS THE DESEQUILIBRED FORCES AT PREVIOUS ITERATION (ELASTOPLASTICITY)
!     GRAND_ACUM_NOD: MATRIX THAT CONTAINS AXIAL FORCE AND PLASTIC STRAIN FOR EACH LOCAL FE NODE IN ROW
!     PL_STRAIN_NOD(I): VECTOR THAT CONTAINS PLASTIC STRAIN FOR EACH GLOCAL NODE (I) OF REINFORCEMENTS MESH (MEAN VALUE OF ELEMENTS THAT THIS NODE BELONGS)
!     NODE_HIST: GIVE INFORMATION ABOUT THE NEED FOR HISTORIC DISPLACEMENT INFORMATION (B: BOUNDARY NODE, I: INTERNAL NODE, N: NONE)
!     N_NODE_HIST: STORE WHICH COLLOCATION POINT (OR INTERNAL POINT) IS THE NODE HISTORIC TO BE PLOTED
!     REINFORCEMENTS_SLIP: 'Y' OR 'N' FOR THE NON-LINEAR ANALYSIS OF BOUND-SLIP EFFECTS IN THE REINFORCEMENTS
!     SLIP_REINF: LOGYCAL VARIABLE TO DETERMINE THE USE OF BOUND-SLIP EFFECTS IN THE ANALYSIS
!     SLIP_PARAMETERS: VECTOR THAT CONTAINS THE PARAMETERS FOR EACH SLIP LAW, ORDER INFORM IN REINFORCEMENTS.F90
!     NODAL_FORCES_PLACE(I,J): CONTAINS, FOR EACH APPLIED NODAL DISPLACEMENT I: NUMBER OF GLOBAL NODE (J=1) AND DIRECTION (J=2), 1=X,2=Y,3=Z
!     NODAL_FORCES_VALUE(I): CONTAIS THE VALUE OF THE (I) APPLIED NODAL DISPLACEMENT
!     N_NODAL_FORCES: NUMBER OF APPLIED NODAL DISPLACEMENTS IN THE FE NODES
!     F_APP_DISP(I): REACTION CONCENTRATED FORCE IN THE DISPLACEMENTS APPLIED NODES (NODAL_FORCES_PLACE)
!     KGLOBAL_NEW: NEW KGLOBAL OBTAINED WITH THE CONNECTION ELEMENTS TO APPLY DISPLACAMENTS AT FIBER NODES
!     GGLOBAL_NEW: NEW GGLOBAL OBTAINED WITH THE CONNECTION ELEMENTS TO APPLY DISPLACAMENTS AT FIBER NODES
!   
!******************************************************************************************************************************   
    
!
!******************************************************************************************************************************    
    MODULE VISCO

    LOGICAL::VISCO_ANALYSIS    
    
    LOGICAL,DIMENSION(:),ALLOCATABLE::BOUND_PNT_VISCO_COLLOC

    INTEGER*4::N_NODES_BOUND_VISCO,N_NODES_INT_VISCO
    
    INTEGER*4,PARAMETER::COUNT_TXT=200
    
    INTEGER*4,DIMENSION(:),ALLOCATABLE::TIME_MODEL,FINAL_STEP_NUMBER,COLLOCPOINTS_VISCO,IPVT_AG,NDI_VISCO,ELEMS_BOUND_PNT_VISCO
    
    REAL*8::DELTA_T_VISCO,NP_TIME
    
    REAL*8,DIMENSION(:),ALLOCATABLE::U_ANTERIOR,T_ANTERIOR,S_ANTERIOR,S_EL_ANTERIOR,U_INT_ANTERIOR,S_EL,FS,S_VISCOSA,S_INT_VISCO,&
        U_INT_VISCO
    
    REAL*8,DIMENSION(:,:),ALLOCATABLE::EMP_VISCO,COORDS_BOUND_VISCO,COORDS_INT_VISCO,HB,HBB,GB,GBB,A_GLOBAL_LU,HH1,HH2,GG1,GG2,&
        HHH1,HHH2,GGG1,GGG2,GG1F,GG2F,GGG1F,GGG2F,QSIS_BOUND_PNT_VISCO
    
    REAL*8,DIMENSION(:,:),ALLOCATABLE,TARGET::B_GLOBAL
    
    REAL*8,DIMENSION(:,:),POINTER::K_KGLOBAL,G_GGLOBAL,HH_FC,GG_FC,GG_FF,GG_CF
       
    END MODULE
    
! EMP_VISCO(I,J): VISCOELASTIC PARAMTERS (J=1) AND BOLTZMAN'S ELASTIC MODULE 2 (J=2) FOR EACH DOMAIN I
! TIME_MODEL(I): FOR EACH DOMAIN, 1 FOR KELVIN, 2 FOR MAXWELL, 3 FOR BOLTZMANN AND 4 FOR HOOKE
! DELTA_T_VISCO: TIME STEP SIZE    
! N_NODES_BOUND_VISCO: NUMBER OF NODES TO OBTAIN TIME RESULTS AT THE BOUNDARY
! COORDS_BOUND_VISCO: X,Y,Z COORDINATES OF THE ABOVE EXPLAINED NODES
! N_NODES_INT_VISCO: NUMBER OF INTERNAL NODES TO OBTAIN TIME RESULTS
! COORDS_INT_VISCO: X,Y,Z COORDINATES OF THE ABOVE EXPLAINED NODES
! FINAL_STEP_NUMBER(I): NUMBER OF TIME STEPS FOR EACH LOAD PHASE I
! NP_TIME: TOTAL NUMBER OF TIME STEPS (UP TO THE END OF THE ANALYSIS)
! COUNT_TXT: AUXILIAR VARIABLE FOR THE OUTPUT TXTS WRITING IN THE VISCOELASTIC ANALYSIS (BOUNDARY TXTS=I+COUNT, INTERNAL TXTS=I+2COUNT)
! COLLOCPOINTS_VISCO(i): VARIABLE THAT CONTAINS THE GLOBAL COLLOCATION POINT NUMBER OF THE I NODE THAT WILL BE ANALYSED IN THE VISCOELASTIC PROBLEM
! U_ANTERIOR and T_ANTERIOR: DISPLACEMENTS AND TRACTIONS VALUES AT EACH NODE DIRECTION AT THE PREVIOUS TIME STEP
! S_EL_ANTERIOR, S_ANTERIOR and U_INT_ANTERIOR: ELASTIC STRESS, TOTAL STRESS AND DISPLACEMENTS IN THE INTERNAL NODES AT THE PREVIOUS TIME STEP
! FS : INDEPENDENT VECTOR AT THE PAST TIME
! S_EL, S_VISCOSA and S_INT_VISCO: ELASTIC SRESS, VISCOUS STRESS AND TOTAL STRESS IN THE INTERNAL NODES AT THE CURRENT TIME STEP 
! A_GLOBAL_LU: MATRIX THAT CONTAINS THE LU FACTORIZATION OF THE A MATRIX FROM Ax=b, TO BE STORED FOR THE FOLLOWING TIME STEPS IN THE VISCOELASTIC ANALYSIS
! IPVT_AG: ARRAY CONTAINING PIVOT INFORMATION ABOU A_GLOBAL_LU NECESSARY TO THE SYSTEM SOLVE
! NDI_VISCO: ARRAY CONTAINING DOMAIN NUMBER OF EACH INTERNAL POINT FROM VISCOELASTIC ANALYSIS
!     HH1,HH2,GG1,GG2 = MATRIXES USED TO CALCULATE DE DISPLACEMENT AT THE INTERNAL POINT
!     HHH1,HHH2,GGG1,GGG2 = MATRIXES USED TO CALCULATE DE STRESS AT THE INTERNAL POINT
! STRESSES POSITIONS: S(1)=SIG_X S(2)=TAU_XY S(3)=TAU_XZ S(4)=TAU_XY S(5)=SIG_Y S(6)=TAU_YZ S(7)=TAU_XZ S(8)=TAU_YZ S(9)=SIG_Z
    
    
!
!******************************************************************************************************************************    
MODULE PRE_REINFORCEMENTS
    
    CHARACTER*1::TIPO_F
    CHARACTER*30::TIPO_DIST_F
    CHARACTER*100::FILE_NAME,ESPACO
    
    LOGICAL::DIST_F
    
    INTEGER::N_FIBER,ORD,NUM_EL[ALLOCATABLE](:),N_ELEMS,N_NODES,CONECTI[ALLOCATABLE](:,:),N_NODES_MAX,&
        MODEL[ALLOCATABLE](:),N_MATERIALS,MATERIALS[ALLOCATABLE](:),FE_MATERIAL[ALLOCATABLE](:),&
        ELASTOPLASTIC,LOAD_STEPS,BOND_SLIP,FIBER_DOMAIN[ALLOCATABLE](:),FE_DOMAIN[ALLOCATABLE](:)
    
    REAL*8,DIMENSION(:,:),ALLOCATABLE::INITIAL_POINTS,FINAL_POINTS,COORD_NODES,MAT_PROP,MAT_PROP_EP
        
    REAL*8::TOL,MEDIA_INC_F(2),DESV_PAD_INC_F(2)
    
    REAL*8,PARAMETER::TOLER=1E-9
    
    ! PARTE DAS FIBRAS ALEATORIAS
    REAL*8::RAIO,LX,F_COMP,F_RAIO,FRACAO,YOUNG_F,AREA_F,LX0,LY0,LY,LZ0,LZ
    INTEGER::NUM_EL_F,ORD_F
    
END MODULE
!******************************************************************************************************************************