SUBROUTINE SHAPE_FUNCTIONS_1D(FLAG,QSI,DEGREE,VALUES,COEFFICIENTS,X,Y,Z,PHI,DPHI)
!	IN THIS SUBROUTINE, THE USER MUST INFORM THE QSI, THE DEGREE OF THE 
!	1D ELEMENT, THE VALUES TO BE INTERPOLATED AND THE RESULTS ARE STORED IN
!	X1, X2, X3, PHI AND DPHI VARIABLES
!
!	[NOT YET IMPLEMENTED] IF FLAG=1, A VALUE IS INTERPOLATED USING THE SHAPE FUNCTIONS
!	THE RESULTS ARE STORED IN X, Y AND Z VARIABLES.
!	IF FLAG=2, THE VALUES OF THE INTERPOLATION FUNCTIONS ARE CALCULATED FOR THE 
!	GIVEN ADIMENSIONAL COORDINATE QSI. THE RESULTS ARE STORED IN PHI VARIABLE
!	IF FLAG=3, THE FIRST DERIVATIVES OF THE SHAPE FUNCTIONS 
!   AT THE GIVEN ADIMENSIONAL COORDINATE QSI ARE CALCULATED ARE CALCULATED.THE RESULTS ARE STORED IN DPHI VARIABLE
!	[NOT YET IMPLEMENTED] IF FLAG=4 THE FIRST DERIVATIVES OF THE INTERPOLATION FUNCTIONS AT THE GIVEN ADIMENSIONAL
!	COORDINATE QSI ARE CALCULATED.THE RESULTS ARE STORED IN DPHI VARIABLE
!	[NOT YET IMPLEMENTED] IF FLAG=5, THE SECOND DERIVATIVES OF THE SHAPE FUNCTIONS AT THE GIVEN ADIMENSIONAL
!	COORDINATE QSI ARE CALCULATED. THE RESULTS ARE STORED IN D2PHI VARIABLE
!   VALUES = NODAL OR COLLOCATION POINTS VALUES THAT ARE USED TOGETHER WITH THE SHAPE FUNCTIONS TO INTERPOLATE     
    INTEGER::FLAG,I,J,DEGREE
    REAL*8::QSI,NODAL_POINTS(DEGREE+1),SPACEMENT,VALUES(DEGREE+1,3),X,Y,Z,PHI(DEGREE+1),DPHI(DEGREE+1),COEFFICIENTS(DEGREE+1),AUX1
!        
    SELECT CASE(FLAG)
    CASE(2)
        PHI=1.0D0
        DO I=1,DEGREE+1
            DO J=1,DEGREE+1
                IF(J.NE.I)THEN
                    PHI(I)=PHI(I)*((QSI-COEFFICIENTS(J))/(COEFFICIENTS(I)-COEFFICIENTS(J)))
                ENDIF
            ENDDO
        ENDDO
    CASE(3)
        DPHI=0.D0
        DO I=1,DEGREE+1
            DO J=1,DEGREE+1
                IF(J.NE.I)THEN
                    AUX1=1.D0
                    DO K=1,DEGREE+1
                        IF(K.NE.I.AND.K.NE.J)THEN
                            AUX1=AUX1*((QSI-COEFFICIENTS(K))/(COEFFICIENTS(I)-COEFFICIENTS(K)))
                        ENDIF
                    ENDDO
                    DPHI(I)=DPHI(I)+AUX1/((COEFFICIENTS(I)-COEFFICIENTS(J)))
                ENDIF
            ENDDO
        ENDDO
    END SELECT
END SUBROUTINE