	SUBROUTINE VERTICAL_INCREMENTS
!	
    USE CRACKS_DUAL_BEM
	USE PROPAGATION	   
!
    IMPLICIT NONE
    INTEGER::I
    REAL*8::Ld,K(2,2),Kinv(2,2),F(2),W(2),DAmin,Wmax,BETA_SCHOLLMANN
!   SCHOLLMANN'S CRITERION BETA    
    BETA_SCHOLLMANN=0.1D0
!    
    K(1,1)=433.D0/35.D0
    K(1,2)=-415.5D0/35.D0
    K(2,1)=-415.5D0/35.D0
    K(2,2)=433.D0/35.D0
    
    CALL DLINRG(2,K,2,Kinv,2)
    
    DO I=1,N_CRACKTIPS
        IF(MOD(I,2).NE.0.D0)THEN
            Ld=DSQRT((COORD_CRACKTIP(I+1,1)-COORD_CRACKTIP(I,1))**2+(COORD_CRACKTIP(I+1,2)-COORD_CRACKTIP(I,2))**2+(COORD_CRACKTIP(I+1,3)-COORD_CRACKTIP(I,3))**2)
            F(1)=(-1271.D0*Ld*PHIP(I)-1253.5D0*Ld*PHIP(I+1))/210.D0
            F(2)=(1253.5D0*Ld*PHIP(I)+1271.D0*Ld*PHIP(I+1))/210.D0
            W=MATMUL(Kinv,F)           
            VERTICAL_INCREMENT(I)=W(1)
            VERTICAL_INCREMENT(I+1)=W(2)           
        ENDIF
    ENDDO
    
    DAmin=10.D0**300
    Wmax=0.D0
    DO I=1,N_CRACKTIPS
        IF(CRACK_INCREMENT(I).LT.DAmin)THEN
            DAmin=CRACK_INCREMENT(I)
        ENDIF
        IF(ABS(VERTICAL_INCREMENT(I)).GT.Wmax)THEN
            Wmax=ABS(VERTICAL_INCREMENT(I))
        ENDIF
    ENDDO
!   
    IF(Wmax.GT.0.D0)THEN    
        DO I=1,N_CRACKTIPS
            ! SCHOLLMANN'S CRITERION BETA IS UTILIZED HERE!
            VERTICAL_INCREMENT(I)=BETA_SCHOLLMANN*DAmin*VERTICAL_INCREMENT(I)/Wmax
        ENDDO
    ENDIF
!
    END SUBROUTINE VERTICAL_INCREMENTS        