    SUBROUTINE WILLIAMS_DISPL_FUNCTIONS(R_TIP,THETA_TIP,Mu,Nu,PSI_TIP)
!   R_TIP: DISTANCE BETWEEN POINT AND CRACK FRONT
!   THETA_TIPO: ANGLE BETWEEN POINT AND CRACK FRONT COORDINATE SYSTEM

    USE ISOPARAMETRIC_MESH
	USE MATERIALS
	USE CRACKS_DUAL_BEM
	USE SUB_REGIONS_INTERFACES
	USE ANALYSIS
    USE XBEM_SUPPORT_VARIABLES
!   
    IMPLICIT NONE
    INTEGER::I,J,ELEM_NODE
!
    REAL*8::PSI_TIP(3,3),Mu,Nu,Kos,PI,R_TIP,THETA_TIP
!
    PI=DACOS(-1.D0)
!   KOSOLOV CONSTANT FOR PLANE STRAIN
    Kos=3.D0-4.D0*Nu
!   WILLIAMS DISPLACEMENT EXPANSIONS - ACCORDING TO ALATAWI (2017) P. 126
    PSI_TIP(1,1)=COS(THETA_TIP/2)*(Kos-1+2*SIN(THETA_TIP/2)**2)
    PSI_TIP(1,2)=SIN(THETA_TIP/2)*(Kos+1+2*COS(THETA_TIP/2)**2)
    PSI_TIP(1,3)=0.D0
    PSI_TIP(2,1)=SIN(THETA_TIP/2)*(Kos+1-2*COS(THETA_TIP/2)**2)
    PSI_TIP(2,2)=-COS(THETA_TIP/2)*(Kos-1-2*SIN(THETA_TIP/2)**2)
    PSI_TIP(2,3)=0.D0
    PSI_TIP(3,1)=0.D0
    PSI_TIP(3,2)=0.D0
    PSI_TIP(3,3)=SIN(THETA_TIP/2)
!
    PSI_TIP=PSI_TIP*(1.D0/(2*Mu))*DSQRT(R_TIP/(2.D0*PI))
!
    END SUBROUTINE WILLIAMS_DISPL_FUNCTIONS