    SUBROUTINE XBEM_CRACK_TIP(A,DIM_XBEM_CRACKFRONT)
!
    USE ISOPARAMETRIC_MESH
	USE MATERIALS
	USE CRACKS_DUAL_BEM
	USE SUB_REGIONS_INTERFACES
	USE ANALYSIS
    USE XBEM_CRACKFRONT_VARIABLES 
    USE PROPAGATION
!
	IMPLICIT NONE 
!
	INTEGER::I,J,K,L,II,JJ,KK,JJJ,NEN,N,KKJ,N_CT_ELEM,H_ENR(N_CRACKTIPS,3),&
    DIM_XBEM_CRACKFRONT,ELEM,POS_COL,POS_LIN,NODE_S,NODE_H,POS_CT_PAIR,NUM_CT_PAIR,DOMAIN,&
    QSI_REF,N_ENRICHED_ELEM,ELEM_CT_S,ELEM_CT_H,ELEM_AL,NEN_AL,POS_AL
!
	REAL*8::DH_ENR[ALLOCATABLE](:,:),A(DIM_XBEM_CRACKFRONT,DIM_XBEM_CRACKFRONT),DX,DY,DZ,DR,&
    COEFFICIENTS_S(N_ALIGNMENT_NODES),COEFFICIENTS_H(N_ALIGNMENT_NODES),VALUES_ALIGN(N_ALIGNMENT_NODES,3),&
    PHI_S(N_ALIGNMENT_NODES),PHI_H(N_ALIGNMENT_NODES),DPHI1D_S(N_ALIGNMENT_NODES),DPHI1D_H(N_ALIGNMENT_NODES),QSI1D_CT,Mu,Nu,&
    VALUES[ALLOCATABLE](:,:),COEFFICIENTS[ALLOCATABLE](:,:),X,Y,Z,PHI[ALLOCATABLE](:),DPHI[ALLOCATABLE](:,:),&
    D2PHI[ALLOCATABLE](:,:,:),ETA(3),VJC(3),DVJC(3,2),JC,DR_DQSI1_CT(3),DR_DQSI2_CT(3),&
    R_TIP_COLLOC,THETA_TIP_COLLOC,&
    PSI_TIP_COLLOCPNT_S[ALLOCATABLE](:,:,:),PSI_TIP_COLLOCPNT_H[ALLOCATABLE](:,:,:),&
    Z_FUN_COLLOCPNT_S[ALLOCATABLE](:,:,:),Z_FUN_COLLOCPNT_H[ALLOCATABLE](:,:,:),&
    ROTATION_MATRIX(3,3),DPHI1D[ALLOCATABLE](:),QSI1D_AL_CP[ALLOCATABLE](:),&
    COEFFICIENTS_K_ALIGN[ALLOCATABLE](:),COORDS_TIP(3),COORDS_CP_PROJECTION(3),QSI_PNT(2),&
    VALUES_K_ALIGN[ALLOCATABLE](:,:),PSI_TIP_AUX(3,3),VALUES_AL[ALLOCATABLE](:,:),&
    VALUES_S[ALLOCATABLE](:,:),VALUES_H[ALLOCATABLE](:,:)
!
    ROTATION_MATRIX=0.D0
    ROTATION_MATRIX(1,1)=1.D0
    ROTATION_MATRIX(2,2)=1.D0
    ROTATION_MATRIX(3,3)=1.D0
    N_CT_ELEM=SIZE(CRACK_TIP_PAIR,1)
    N=N_GAUSSPOINTS
    VALUES_ALIGN=0.D0
    N_ENRICHED_ELEM=SIZE(ENRICHED_ELEMS,1)
    CALL OMP_SET_NUM_THREADS(24)
!$OMP PARALLEL PRIVATE(I,J,K,II,JJ,KK,JJJ,NEN,DX,DY,DZ,DR,DH_ENR,ELEM,POS_COL)
!$OMP DO SCHEDULE(DYNAMIC)	
  	DO I=1,N_COLLOCPOINTS
        !WRITE(*,*)"COLLOC_POINT:",I," OF:",N_COLLOCPOINTS
		JJ=0
		DO K=1,N_ELEM
		    NEN=ELEM_TYPE(K)*ORDER_ELEM(K)+(ELEM_TYPE(K)-3)*(ORDER_ELEM(K)-1)*POL_FAMILY(K)
			DO KK=1,NEN
				IF(COLLOCPOINTS_CONNECTIVITY(K,KK).EQ.I) THEN
!                   ELEMENT THAT CONTAINS COLLOC POINT I
                    JJ=K
				ENDIF
			ENDDO
	    ENDDO
	    JJJ=ND(JJ)
		DO J=1,N_ENRICHED_ELEM
            ELEM=ENRICHED_ELEMS(J,1)
			IF(ND(JJ).EQ.ND(ELEM)) THEN
!               II VERIFIES IF SOURCE POINT IS INSIDE ELEMENT - SINGULARITY
                II=0
				NEN=ELEM_TYPE(ELEM)*ORDER_ELEM(ELEM)+(ELEM_TYPE(ELEM)-3)*(ORDER_ELEM(ELEM)-1)*POL_FAMILY(ELEM)
				DO K=1,NEN
					IF(COLLOCPOINTS_CONNECTIVITY(ELEM,K).EQ.I) THEN
						II=1
					ENDIF
                ENDDO
!				
				IF(II.EQ.0) THEN
		            DO K=1,NEN
			            DX=COORD_COLLOCPOINTS(COLLOCPOINTS_CONNECTIVITY(ELEM,K),1)-COORD_COLLOCPOINTS(I,1)
			            DY=COORD_COLLOCPOINTS(COLLOCPOINTS_CONNECTIVITY(ELEM,K),2)-COORD_COLLOCPOINTS(I,2)
	                    DZ=COORD_COLLOCPOINTS(COLLOCPOINTS_CONNECTIVITY(ELEM,K),3)-COORD_COLLOCPOINTS(I,3)
			            DR=DSQRT(DX*DX+DY*DY+DZ*DZ)
			            IF(DR.LE.1.E-12) THEN
				            II=1
				        ENDIF
		            ENDDO
                ENDIF
!   
                ALLOCATE(DH_ENR(3*N_K,3))
                DH_ENR=0.D0
!
				IF((II.EQ.1)) THEN
					IF(EQ_TYPE(I).EQ.'S') THEN
                        CALL XBEM_K_SINGULAR_S(I,ELEM,JJJ,DH_ENR,N)
                    ELSE
                        CALL XBEM_K_SINGULAR_HP(I,ELEM,JJJ,DH_ENR,N)
					ENDIF
				ELSE
					IF(ELEM_TYPE(ELEM).EQ.3) THEN    
                        ! DOES NOT WORK!
						!IF(EQ_TYPE(I).EQ.'S')THEN
						!    CALL TRIANGULAR_ELEMENT_S(I,CRACKTIP_PAIR(J,1),JJJ,DG,DH,N)
						!ELSE
						!    CALL TRIANGULAR_ELEMENT_HP(I,CRACKTIP_PAIR(J,1),JJ,JJJ,DG,DH,N) 
						!ENDIF   
					ELSE
                        IF(EQ_TYPE(I).EQ.'S')THEN
                            CALL XBEM_K_QUADRILATERAL_S(I,ELEM,JJJ,DH_ENR,N)
                        ELSE    
                            CALL XBEM_K_QUADRILATERAL_HP(I,ELEM,JJ,JJJ,DH_ENR,N) 
						ENDIF   
					ENDIF
                ENDIF
!$OMP CRITICAL
                DO K=1,N_CRACKTIPS
                    POS_COL=3*N_COLLOCPOINTS+3*(K-1)
                    DO KK=1,N_K
                        IF(ENRICHED_ELEMS(J,KK+1).EQ.CRACKTIP_COLLOCPOINTS(K))THEN
                            A(3*I-2,POS_COL+1)=A(3*I-2,POS_COL+1)+DH_ENR(3*KK-2,1)
				            A(3*I-1,POS_COL+1)=A(3*I-1,POS_COL+1)+DH_ENR(3*KK-1,1)
				            A(3*I,POS_COL+1)=A(3*I,POS_COL+1)+DH_ENR(3*KK,1)
!				    
				            A(3*I-2,POS_COL+2)=A(3*I-2,POS_COL+2)+DH_ENR(3*KK-2,2)
				            A(3*I-1,POS_COL+2)=A(3*I-1,POS_COL+2)+DH_ENR(3*KK-1,2)
				            A(3*I,POS_COL+2)=A(3*I,POS_COL+2)+DH_ENR(3*KK,2)
!				    
				            A(3*I-2,POS_COL+3)=A(3*I-2,POS_COL+3)+DH_ENR(3*KK-2,3)
				            A(3*I-1,POS_COL+3)=A(3*I-1,POS_COL+3)+DH_ENR(3*KK-1,3)
				            A(3*I,POS_COL+3)=A(3*I,POS_COL+3)+DH_ENR(3*KK,3)	
                        ENDIF
                    ENDDO
                ENDDO
!$OMP END CRITICAL                
			    DEALLOCATE(DH_ENR)
	        ENDIF
	    ENDDO 
    ENDDO	
!$OMP END DO
!$OMP END PARALLEL   
!   SUPPLEMENTARY EQUATIONS
    ALLOCATE(PSI_TIP_COLLOCPNT_S(3,3,N_ALIGNMENT_NODES),PSI_TIP_COLLOCPNT_H(3,3,N_ALIGNMENT_NODES),Z_FUN_COLLOCPNT_S(3,3,N_ALIGNMENT_NODES),Z_FUN_COLLOCPNT_H(3,3,N_ALIGNMENT_NODES),QSI1D_AL_CP(N_ALIGNMENT_NODES),COEFFICIENTS_K_ALIGN(N_K),VALUES_K_ALIGN(N_K,3))
    DO I=1,N_CRACKTIPS
!       POSITION OF ASSOCIATED CRACK TIP
        COORDS_TIP(1)=COORD_CRACKTIP(I,1)
        COORDS_TIP(2)=COORD_CRACKTIP(I,2)
        COORDS_TIP(3)=COORD_CRACKTIP(I,3) 
!       FIND POSITION IN CRACK_TIP_PAIR OF CRACK TIP
        DO K=1,N_CT_ELEM
            DO L=1,2
                IF(CRACK_TIP_PAIR(K,L+2).EQ.CRACKTIP_COLLOCPOINTS(I))THEN
                    POS_CT_PAIR=K
!                   NUM_CT_PAIR=1:INITIAL NODE, NUM_CT_PAIR=2:FINAL NODE
                    NUM_CT_PAIR=L   
                ENDIF
            ENDDO
        ENDDO
!       ROTATION MATRIX OF CRACK TIP ASSOCIATED
        !QSI1D_CT=CT_PAIR_QSI(POS_CT_PAIR)
        ELEM_CT_S=CRACK_TIP_PAIR(POS_CT_PAIR,1)
        !ELEM_CT_H=CRACK_TIP_PAIR(POS_CT_PAIR,1)CALCULAR
        
!       QSI_REF=CRACK_TIP_PAIR(POS_CT_PAIR,2)
!       CONSIDERING SAME DOMAIN TO BOTH CRACKED ELEMENTS
        DOMAIN=ND(ELEM_CT_S)
        Mu=EMP(DOMAIN,1)/(2*(1+EMP(DOMAIN,2)))
	    Nu=EMP(DOMAIN,2)
!
      !  NEN=ELEM_TYPE(ELEM_CT_S)*ORDER_ELEM(ELEM_CT_S)+(ELEM_TYPE(ELEM_CT_S)-3)*(ORDER_ELEM(ELEM_CT_S)-1)*POL_FAMILY(ELEM_CT_S)
      !  ALLOCATE(VALUES(NEN,3),COEFFICIENTS(NEN,NEN),PHI(NEN),DPHI(NEN,2),D2PHI(NEN,2,2))
      !  DO J=1,NEN
		    !VALUES_S(J,1)=COORD_NODES(NODES_CONNECTIVITY(ELEM_CT_S,J),1)
		    !VALUES_S(J,2)=COORD_NODES(NODES_CONNECTIVITY(ELEM_CT_S,J),2)
		    !VALUES_S(J,3)=COORD_NODES(NODES_CONNECTIVITY(ELEM_CT_S,J),3)
      !  ENDDO   
!       DEFINING QSI1D_CT - GET BACK WHEN ROTATION WILL BE UNCOMMENTED
!       COEFFICIENTS_K_ALIGN
        !CALL NEWTON_RAPHSON_ADIMENSIONAL_COORDINATES(NEN,VALUES_S,COORDS_TIP,QSI_PNT)
        !IF(QSI_REF.EQ.1)THEN
        !    QSI1D_CT=QSI_PNT(2)
        !ELSE
        !    QSI1D_CT=QSI_PNT(1)
        !ENDIF
!       ROTATION MATRIX
!        IF(QSI_REF.EQ.1)THEN
!            CALL SHAPE_FUNCTIONS(3,CT_PAIR_QSI(POS_CT_PAIR),QSI1D_CT,NEN,VALUES,COEFFICIENTS,X,Y,Z,PHI,DPHI,D2PHI)
!            CALL NORMAL_OUTWARD(NEN,VALUES,QSI1D_CT,CT_PAIR_QSI(POS_CT_PAIR),ETA,VJC,DVJC,JC)
!        ELSE
!            CALL SHAPE_FUNCTIONS(3,QSI1D_CT,CT_PAIR_QSI(POS_CT_PAIR),NEN,VALUES,COEFFICIENTS,X,Y,Z,PHI,DPHI,D2PHI)
!            CALL NORMAL_OUTWARD(NEN,VALUES,CT_PAIR_QSI(POS_CT_PAIR),QSI1D_CT,ETA,VJC,DVJC,JC)
!        ENDIF
!        DR_DQSI1_CT=0.D0
!        DR_DQSI2_CT=0.D0
!        DO K=1,3
!            DO L=1,NEN
!                DR_DQSI1_CT(K)=DR_DQSI1_CT(K)+DPHI(L,1)*VALUES(L,K)
!                DR_DQSI2_CT(K)=DR_DQSI2_CT(K)+DPHI(L,2)*VALUES(L,K)
!            ENDDO
!        ENDDO
!        DR_DQSI1_CT=DR_DQSI1_CT/(DSQRT(DR_DQSI1_CT(1)**2+DR_DQSI1_CT(2)**2+DR_DQSI1_CT(3)**2))
!        DR_DQSI2_CT=DR_DQSI2_CT/(DSQRT(DR_DQSI2_CT(1)**2+DR_DQSI2_CT(2)**2+DR_DQSI2_CT(3)**2))
!!       CHANGE DIRECTION OF NORMAL OUTWARD BECAUSE DISPLACEMENT EQUATION
!        IF(DUAL_BEM(COLLOCPOINTS_CONNECTIVITY(ELEM_CT,1)).EQ."S")THEN
!            ETA=-ETA
!            !DR_DQSI1_CT=-DR_DQSI1_CT
!            !DR_DQSI2_CT=-DR_DQSI2_CT
!        ENDIF
!        IF(QSI_REF.EQ.1)THEN
!            ROTATION_MATRIX(:,1)=DR_DQSI1_CT
!            ROTATION_MATRIX(:,2)=ETA
!            ROTATION_MATRIX(:,3)=DR_DQSI2_CT
!        ELSE
!            ROTATION_MATRIX(:,1)=DR_DQSI2_CT
!            ROTATION_MATRIX(:,2)=ETA
!            ROTATION_MATRIX(:,3)=DR_DQSI1_CT
!        ENDIF                       
!       WILLIAMS DISPL FUNCTIONS OF EACH COLLOCATION POINT ALIGNED TO CRACK TIP: NODE_S
        Z_FUN_COLLOCPNT_S=0.D0
        PSI_TIP_COLLOCPNT_S=0.D0
        PSI_TIP_COLLOCPNT_H=0.D0
        DO K=1,N_ALIGNMENT_NODES
            NODE_S=ALIGN_ELEM_S_NODE(K,I)
            DO J=1,N_ELEM
                NEN_AL=ELEM_TYPE(J)*ORDER_ELEM(J)+(ELEM_TYPE(J)-3)*(ORDER_ELEM(J)-1)*POL_FAMILY(J)
                DO II=1,NEN_AL
                    IF(COLLOCPOINTS_CONNECTIVITY(J,II).EQ.NODE_S)THEN
                        ELEM_AL=J
                    ENDIF
                ENDDO
            ENDDO
            NEN_AL=ELEM_TYPE(ELEM_AL)*ORDER_ELEM(ELEM_AL)+(ELEM_TYPE(ELEM_AL)-3)*(ORDER_ELEM(ELEM_AL)-1)*POL_FAMILY(ELEM_AL)
            ALLOCATE(VALUES_AL(NEN_AL,3))
            DO J=1,NEN
		        VALUES_AL(J,1)=COORD_NODES(NODES_CONNECTIVITY(ELEM_AL,J),1)
		        VALUES_AL(J,2)=COORD_NODES(NODES_CONNECTIVITY(ELEM_AL,J),2)
		        VALUES_AL(J,3)=COORD_NODES(NODES_CONNECTIVITY(ELEM_AL,J),3)
            ENDDO   
!
            COORDS_CP_PROJECTION=COORD_COLLOCPOINTS(NODE_S,:)
            DX=COORDS_CP_PROJECTION(1)-COORDS_TIP(1)
            DY=COORDS_CP_PROJECTION(2)-COORDS_TIP(2)
            DZ=COORDS_CP_PROJECTION(3)-COORDS_TIP(3)
            R_TIP_COLLOC=DSQRT(DX*DX+DY*DY+DZ*DZ)
            THETA_TIP_COLLOC=DACOS((ROTATION_MATRIX(1,1)*DX+ROTATION_MATRIX(2,1)*DY+ROTATION_MATRIX(3,1)*DZ)/R_TIP_COLLOC)
!           WILLIAMS DISPL FUNCTIONS OF CRACK TIP AND SOURCE POINT        
            CALL WILLIAMS_DISPL_FUNCTIONS(R_TIP_COLLOC,THETA_TIP_COLLOC,Mu,Nu,PSI_TIP_COLLOCPNT_S(:,:,K))
            PSI_TIP_AUX=PSI_TIP_COLLOCPNT_S(:,:,K)
            CALL DMRRRR(3,3,ROTATION_MATRIX,3,3,3,PSI_TIP_AUX,3,3,3,Z_FUN_COLLOCPNT_S(:,:,K),3)
            DEALLOCATE(VALUES_AL)
        ENDDO
!       WILLIAMS DISPL FUNCTIONS OF EACH COLLOCATION POINT ALIGNED TO CRACK TIP: NODE_H
        Z_FUN_COLLOCPNT_H=0.D0
        DO K=1,N_ALIGNMENT_NODES
            NODE_H=ALIGN_ELEM_H_NODE(K,I)
            DO J=1,N_ELEM
                NEN_AL=ELEM_TYPE(J)*ORDER_ELEM(J)+(ELEM_TYPE(J)-3)*(ORDER_ELEM(J)-1)*POL_FAMILY(J)
                DO II=1,NEN_AL
                    IF(COLLOCPOINTS_CONNECTIVITY(K,II).EQ.NODE_H)THEN
                        ELEM_AL=J
                    ENDIF
                ENDDO
            ENDDO
            NEN_AL=ELEM_TYPE(ELEM_AL)*ORDER_ELEM(ELEM_AL)+(ELEM_TYPE(ELEM_AL)-3)*(ORDER_ELEM(ELEM_AL)-1)*POL_FAMILY(ELEM_AL)
            ALLOCATE(VALUES_AL(NEN_AL,3))
            DO J=1,NEN
		        VALUES_AL(J,1)=COORD_NODES(NODES_CONNECTIVITY(ELEM_AL,J),1)
		        VALUES_AL(J,2)=COORD_NODES(NODES_CONNECTIVITY(ELEM_AL,J),2)
		        VALUES_AL(J,3)=COORD_NODES(NODES_CONNECTIVITY(ELEM_AL,J),3)
            ENDDO   
!
            COORDS_CP_PROJECTION=COORD_COLLOCPOINTS(NODE_H,:)
            DX=COORDS_CP_PROJECTION(1)-COORDS_TIP(1)
            DY=COORDS_CP_PROJECTION(2)-COORDS_TIP(2)
            DZ=COORDS_CP_PROJECTION(3)-COORDS_TIP(3)
            R_TIP_COLLOC=DSQRT(DX*DX+DY*DY+DZ*DZ)
            THETA_TIP_COLLOC=-DACOS((ROTATION_MATRIX(1,1)*DX+ROTATION_MATRIX(2,1)*DY+ROTATION_MATRIX(3,1)*DZ)/R_TIP_COLLOC)
!           WILLIAMS DISPL FUNCTIONS OF CRACK TIP AND SOURCE POINT        
            CALL WILLIAMS_DISPL_FUNCTIONS(R_TIP_COLLOC,THETA_TIP_COLLOC,Mu,Nu,PSI_TIP_COLLOCPNT_H(:,:,K))
            PSI_TIP_AUX=PSI_TIP_COLLOCPNT_H(:,:,K)
            CALL DMRRRR(3,3,ROTATION_MATRIX,3,3,3,PSI_TIP_AUX,3,3,3,Z_FUN_COLLOCPNT_H(:,:,K),3)
            DEALLOCATE(VALUES_AL)
        ENDDO
!   
        POS_LIN=3*N_COLLOCPOINTS+3*(I-1)
        POS_COL=3*N_COLLOCPOINTS+3*(I-1)
        DO J=1,N_ALIGNMENT_NODES
            COEFFICIENTS_S(J)=ALIGN_ELEM_S_QSI(J,I)
            COEFFICIENTS_H(J)=ALIGN_ELEM_H_QSI(J,I)
        ENDDO
        CALL SHAPE_FUNCTIONS_1D(2,1.D0,N_ALIGNMENT_NODES-1,VALUES_ALIGN,COEFFICIENTS_S,X,Y,Z,PHI_S,DPHI1D_S)
        CALL SHAPE_FUNCTIONS_1D(2,-1.D0,N_ALIGNMENT_NODES-1,VALUES_ALIGN,COEFFICIENTS_H,X,Y,Z,PHI_H,DPHI1D_H)
!
        DO J=1,N_ALIGNMENT_NODES
            NODE_S=ALIGN_ELEM_S_NODE(J,I) 
            NODE_H=ALIGN_ELEM_H_NODE(J,I)
!           DISPLACEMENT EQN CRACK FACE
            A(POS_LIN+1,3*NODE_S-2)=A(POS_LIN+1,3*NODE_S-2)+PHI_S(J)
            A(POS_LIN+2,3*NODE_S-1)=A(POS_LIN+2,3*NODE_S-1)+PHI_S(J)
            A(POS_LIN+3,3*NODE_S)=A(POS_LIN+3,3*NODE_S)+PHI_S(J)
!           TRACTION EQN CRACK FACE       
            A(POS_LIN+1,3*NODE_H-2)=A(POS_LIN+1,3*NODE_H-2)-PHI_H(J)
            A(POS_LIN+2,3*NODE_H-1)=A(POS_LIN+2,3*NODE_H-1)-PHI_H(J)
            A(POS_LIN+3,3*NODE_H)=A(POS_LIN+3,3*NODE_H)-PHI_H(J)
        ENDDO
!       CRACK TIP PSI CONTRIBUTION
        DO K=1,3    ! K IS ASSOCIATED TO SIF COLUMNS 
            DO L=1,3    ! L IS ASSOCIATED TO DIRECTION OF EQN 
                DO KK=1,N_ALIGNMENT_NODES   ! KK IS ASSOCIATED TO INTERNAL SUM
                    A(POS_LIN+L,POS_COL+K)=A(POS_LIN+L,POS_COL+K)+(PHI_H(KK)*Z_FUN_COLLOCPNT_H(L,K,KK)-PHI_S(KK)*Z_FUN_COLLOCPNT_S(L,K,KK))
                ENDDO
            ENDDO
        ENDDO
        !DEALLOCATE(COEFFICIENTS,PHI,DPHI,D2PHI)!VALUES,
!      
    ENDDO
    !   WRITE TXT FILE TO SEE ENRICHED MATRIX
    OPEN(6,file='MATRIZ A.txt',status='unknown')
    !WRITE(5,*)(CRACKTIP_COLLOCPOINTS(K),K=1,N_CRACKTIPS)
    DO I=1,3*N_COLLOCPOINTS+3*N_CRACKTIPS
        WRITE(6,'(10000F)')(A(I,K),K=1,3*N_COLLOCPOINTS+3*N_CRACKTIPS)
    ENDDO
    CLOSE(6)
    DEALLOCATE(PSI_TIP_COLLOCPNT_S,PSI_TIP_COLLOCPNT_H,VALUES_K_ALIGN,COEFFICIENTS_K_ALIGN)
!    	   
    END SUBROUTINE XBEM_CRACK_TIP
