	SUBROUTINE XBEM_K_AUXILIAR_ELEMS
!	
    USE ISOPARAMETRIC_MESH
    USE MATERIALS
	USE CRACKS_DUAL_BEM
	USE SUB_REGIONS_INTERFACES
	USE ANALYSIS
	USE REMESHING
	USE PROPAGATION	   
	USE FATIGUE
    USE XBEM_CRACKFRONT_VARIABLES
!
    IMPLICIT NONE
!   CRACK_TIP_PAIR ONLY FOR LINEAR ELEMENTS
    INTEGER::I,J,K,II,JJ,KK,ELEMENT,LOCAL_NUMBER,NEN,CP_S1,CP_S2,CP_H1,CP_H2,CONT,CONTS,CONTH,STEP,AUX_INT,&
    CRACK_TIP_FOUND,POSITION_CT,NODE_CT,NODE_CT2,COLLOC_TEST,AUX_ALIGNMENT_NODE_H(SIZE(NC,1)),AUX_ALIGNMENT_NODE_S(SIZE(NC,1)),&
    COMP_ALIGNMENT_NODE_S[ALLOCATABLE](:,:),COMP_ALIGNMENT_NODE_H[ALLOCATABLE](:,:)
!    
    REAL*8::R,PI,DX,DY,DZ!,THETA,GTHETA,GTHETA_AUX,,R1,R2,COD1,COD2,CSD1,CSD2,CTD1,CTD2,KI1,KI2,KII1,KII2,KIII1,KIII2,E,Nu,KIC,PI
    REAL*8::VALUES[ALLOCATABLE](:,:),COEFFICIENTS[ALLOCATABLE](:,:),PHI[ALLOCATABLE](:),DPHI[ALLOCATABLE](:,:),D2PHI[ALLOCATABLE](:,:,:),&
    QSI_NODE_I(2),QSI_NODE_F(2),COORDS_PNT(3),VEC_CRACK(3),VEC_AUX(3),ALPHA_COS,AUX1,NORM_VEC_CRACK,NORM_VEC_AUX,&
    AUX_ALIGNMENT_DIST_S(SIZE(NC,1)),AUX_ALIGNMENT_DIST_H(SIZE(NC,1)),L_ELEM_S,L_ELEM_H,L_NODE_CT
    
!
    CHARACTER(40)::NOME	     
!
	PI=DACOS(-1.D0)
    N_CRACKTIPS=0  
    DO I=1,N_COLLOCPOINTS
        IF(CRACK_TIP(I).EQ.1.AND.DUAL_BEM(I).EQ."S")THEN
            N_CRACKTIPS=N_CRACKTIPS+1
        ENDIF
        IF(CRACK_TIP(I).EQ.3.AND.DUAL_BEM(I).EQ."S")THEN
            N_CRACKTIPS=N_CRACKTIPS+1
        ENDIF        
    ENDDO
    
    ALLOCATE(COORD_CRACKTIP(N_CRACKTIPS,3))
    ALLOCATE(COMP_ALIGNMENT_NODE_S(N_ENRICHED_ELEMS,N_CRACKTIPS),COMP_ALIGNMENT_NODE_H(N_ENRICHED_ELEMS,N_CRACKTIPS))
    ALLOCATE(THETAP(N_CRACKTIPS),PHIP(N_CRACKTIPS),Keq(N_CRACKTIPS),Gmax(N_CRACKTIPS),CRACK_INCREMENT(N_CRACKTIPS),VERTICAL_INCREMENT(N_CRACKTIPS))
    ALLOCATE(CRACKTIP_COLLOCPOINTS(N_CRACKTIPS),ALIGN_ELEM_S_NODE(N_ALIGNMENT_NODES,N_CRACKTIPS),ALIGN_ELEM_H_NODE(N_ALIGNMENT_NODES,N_CRACKTIPS))
    ALLOCATE(ALIGN_ELEM_S_QSI(N_ALIGNMENT_NODES,N_CRACKTIPS),ALIGN_ELEM_H_QSI(N_ALIGNMENT_NODES,N_CRACKTIPS))
!   CHANGE LATER WHEN QUADRATIC ELEMENTS ARE USED
    ALLOCATE(CRACK_TIP_PAIR(N_CRACKTIPS/2,4),CT_PAIR_QSI(N_CRACKTIPS/2))
! --------------------------------------------------------------------------------------------------------------------------------------------------
!   DEFINING COORDINATES OF EACH CRACK TIP
! --------------------------------------------------------------------------------------------------------------------------------------------------   
    CONT=0 
    PI=DACOS(-1.D0)
    DO I=1,N_COLLOCPOINTS
        IF(CRACK_TIP(I).EQ.1.AND.DUAL_BEM(I).EQ."S")THEN
            CP_S1=I
            CONT=CONT+1
!            
            DO J=1,N_ELEM
                NEN=ELEM_TYPE(J)*ORDER_ELEM(J)+(ELEM_TYPE(J)-3)*(ORDER_ELEM(J)-1)*POL_FAMILY(J)
                DO K=1,NEN
                    IF(COLLOCPOINTS_CONNECTIVITY(J,K).EQ.CP_S1)THEN
                        ELEMENT=J
                        LOCAL_NUMBER=K                    
                    ENDIF
                ENDDO
            ENDDO
!            
            CRACKTIP_COLLOCPOINTS(CONT)=COLLOCPOINTS_CONNECTIVITY(ELEMENT,LOCAL_NUMBER)
!            
            NEN=ELEM_TYPE(ELEMENT)*ORDER_ELEM(ELEMENT)+(ELEM_TYPE(ELEMENT)-3)*(ORDER_ELEM(ELEMENT)-1)*POL_FAMILY(ELEMENT)
            ALLOCATE(VALUES(NEN,3))	
	        DO K=1,NEN
		        VALUES(K,1)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),1)
		        VALUES(K,2)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),2)
		        VALUES(K,3)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),3)
	        ENDDO 
	        SELECT CASE(LOCAL_NUMBER)
	        CASE(1)
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN                      	            
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE
                    CALL SHAPE_FUNCTIONS(1,-0.8D0,-1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ENDIF  
            CASE(2)
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN                                    
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE
                    CALL SHAPE_FUNCTIONS(1,0.8D0,-1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ENDIF
            CASE(3)
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                  
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.3)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE
                    CALL SHAPE_FUNCTIONS(1,1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ENDIF
            CASE(4)                                     
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.3.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE
                    CALL SHAPE_FUNCTIONS(1,-0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ENDIF             	        	        
	        ENDSELECT          
            DEALLOCATE(VALUES)                    
        ELSE IF(CRACK_TIP(I).EQ.3.AND.DUAL_BEM(I).EQ."S")THEN
            CP_S1=I
            CONT=CONT+1
!            
            DO J=1,N_ELEM
                NEN=ELEM_TYPE(J)*ORDER_ELEM(J)+(ELEM_TYPE(J)-3)*(ORDER_ELEM(J)-1)*POL_FAMILY(J)
                DO K=1,NEN
                    IF(COLLOCPOINTS_CONNECTIVITY(J,K).EQ.CP_S1)THEN
                        ELEMENT=J
                        LOCAL_NUMBER=K                    
                    ENDIF
                ENDDO
            ENDDO
            CRACKTIP_COLLOCPOINTS(CONT)=COLLOCPOINTS_CONNECTIVITY(ELEMENT,LOCAL_NUMBER)            
!            
            NEN=ELEM_TYPE(ELEMENT)*ORDER_ELEM(ELEMENT)+(ELEM_TYPE(ELEMENT)-3)*(ORDER_ELEM(ELEMENT)-1)*POL_FAMILY(ELEMENT)
            ALLOCATE(VALUES(NEN,3))	
	        DO K=1,NEN
		        VALUES(K,1)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),1)
		        VALUES(K,2)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),2)
		        VALUES(K,3)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),3)
	        ENDDO 
	        SELECT CASE(LOCAL_NUMBER)
	        CASE(1)                                         
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE
                    CALL SHAPE_FUNCTIONS(1,-0.8D0,-1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ENDIF  
            CASE(2)                                    
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,1.D0,-0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE
                    CALL SHAPE_FUNCTIONS(1,0.8D0,-1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ENDIF
            CASE(3)                                    
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,4)).EQ.1)THEN
                    CALL SHAPE_FUNCTIONS(1,0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE
                    CALL SHAPE_FUNCTIONS(1,1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ENDIF
            CASE(4)                                                                             
                IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.2.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.0)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI) 
                ELSE IF(CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,1)).EQ.1.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,2)).EQ.0.AND.CRACK_TIP(COLLOCPOINTS_CONNECTIVITY(ELEMENT,3)).EQ.2)THEN
                    CALL SHAPE_FUNCTIONS(1,-1.D0,0.8D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                                                                                                         
                ELSE
                    CALL SHAPE_FUNCTIONS(1,-0.8D0,1.D0,NEN,VALUES,COEFFICIENTS,COORD_CRACKTIP(CONT,1),COORD_CRACKTIP(CONT,2),COORD_CRACKTIP(CONT,3),PHI,DPHI,D2PHI)                      
                ENDIF             	        	        
	        ENDSELECT 
!            	        
            DEALLOCATE(VALUES)                    
        ENDIF         
    ENDDO      
!
!   DEFINING PAIR OF CRACK TIP POINTS IN SAME ELEMENT AND CREATING K INTERPOLATION ELEMENT (INTERPOLATION ONLY LINEAR, MODIFY LATER)
    CRACK_TIP_PAIR=0
    CONT=0
!
    DO I=1,N_CRACKTIPS
!       CRACK_TIP_FOUND DEFINES IF PAIR WAS ALREADY FOUND
        NODE_CT=CRACKTIP_COLLOCPOINTS(I)
        CRACK_TIP_FOUND=1
        DO J=1,N_CRACKTIPS/2
!           CHANGE LATER WHEN QUADRATIC ELEMENTS ARE USED
            DO K=3,4
                IF(CRACK_TIP_PAIR(J,K).EQ.NODE_CT)THEN
                    CRACK_TIP_FOUND=-1
                ENDIF
            ENDDO
        ENDDO
        IF(CRACK_TIP_FOUND.EQ.1)THEN
            CONT=CONT+1
!           FIND ELEMENT ASSOCIATED TO COLLOCATION POINT
            DO J=1,N_ELEM
                NEN=ELEM_TYPE(J)*ORDER_ELEM(J)+(ELEM_TYPE(J)-3)*(ORDER_ELEM(J)-1)*POL_FAMILY(J)
                DO K=1,NEN
                    IF(COLLOCPOINTS_CONNECTIVITY(J,K).EQ.NODE_CT.AND.DUAL_BEM(NODE_CT).EQ."S")THEN
                        ELEMENT=J                 
                    ENDIF
                ENDDO
            ENDDO
!           ELEMENT THAT CONTAINS CRACK TIP PAIR (SINGULAR)
            CRACK_TIP_PAIR(CONT,1)=ELEMENT
!           FIND PAIR OF COLLOCATION POINT INSIDE ELEMENT
            NEN=ELEM_TYPE(ELEMENT)*ORDER_ELEM(ELEMENT)+(ELEM_TYPE(ELEMENT)-3)*(ORDER_ELEM(ELEMENT)-1)*POL_FAMILY(ELEMENT)
            DO J=1,N_CRACKTIPS
                DO K=1,NEN
                    DO II=1,2
                        IF((COLLOCPOINTS_CONNECTIVITY(ELEMENT,K).EQ.CRACKTIP_COLLOCPOINTS(J)).AND.(COLLOCPOINTS_CONNECTIVITY(ELEMENT,K).NE.NODE_CT))THEN
                            CRACK_TIP_PAIR(CONT,3)=NODE_CT
                            CRACK_TIP_PAIR(CONT,4)=CRACKTIP_COLLOCPOINTS(J)
                        ENDIF
                    ENDDO
                ENDDO
            ENDDO
!           CHECKING WHAT ADIMENSIONAL COORDINATE IS EQUAL TO BOTH NODES
            ALLOCATE(VALUES(NEN,3))
            DO K=1,NEN
		        VALUES(K,1)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),1)
		        VALUES(K,2)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),2)
		        VALUES(K,3)=COORD_NODES(NODES_CONNECTIVITY(ELEMENT,K),3)
            ENDDO 
!           INITIAL NODE ADIMENSIONAL COORDINATES
            DO J=1,N_CRACKTIPS
                IF(CRACK_TIP_PAIR(CONT,3).EQ.CRACKTIP_COLLOCPOINTS(J))THEN
                    POSITION_CT=J
                ENDIF
            ENDDO
            COORDS_PNT(1)=COORD_CRACKTIP(POSITION_CT,1)
            COORDS_PNT(2)=COORD_CRACKTIP(POSITION_CT,2)
            COORDS_PNT(3)=COORD_CRACKTIP(POSITION_CT,3)
            CALL NEWTON_RAPHSON_ADIMENSIONAL_COORDINATES(NEN,VALUES,COORDS_PNT,QSI_NODE_I)
!           FINAL NODE ADIMENSIONAL COORDINATES
            DO J=1,N_CRACKTIPS
                IF(CRACK_TIP_PAIR(CONT,4).EQ.CRACKTIP_COLLOCPOINTS(J))THEN
                    POSITION_CT=J
                ENDIF
            ENDDO
            COORDS_PNT(1)=COORD_CRACKTIP(POSITION_CT,1)
            COORDS_PNT(2)=COORD_CRACKTIP(POSITION_CT,2)
            COORDS_PNT(3)=COORD_CRACKTIP(POSITION_CT,3)            
            CALL NEWTON_RAPHSON_ADIMENSIONAL_COORDINATES(NEN,VALUES,COORDS_PNT,QSI_NODE_F)
!           CHECKING QSI1 AND QSI2, WHICH ONE OF THEM IS EQUAL
            IF(ABS(QSI_NODE_I(1)-QSI_NODE_F(1)).LT.1D-8)THEN
                CRACK_TIP_PAIR(CONT,2)=1
                CT_PAIR_QSI(CONT)=QSI_NODE_I(1)
            ELSEIF(ABS(QSI_NODE_I(2)-QSI_NODE_F(2)).LT.1D-8)THEN
                CRACK_TIP_PAIR(CONT,2)=2
                CT_PAIR_QSI(CONT)=QSI_NODE_I(2)
            ENDIF
            DEALLOCATE(VALUES)
        ENDIF
    ENDDO
!   CREATING ALIGNMENT ELEMENT
    AUX_ALIGNMENT_NODE_S=0
    AUX_ALIGNMENT_DIST_S=1.D50
    AUX_ALIGNMENT_NODE_H=0
    AUX_ALIGNMENT_DIST_H=1.D50
    DO I=1,N_CRACKTIPS
        NODE_CT=CRACKTIP_COLLOCPOINTS(I)
!       FINDING PAIR OF COLLOCATION POINTS
        DO J=1,N_CRACKTIPS/2
            IF(NODE_CT.EQ.CRACK_TIP_PAIR(J,3))THEN
                NODE_CT2=CRACK_TIP_PAIR(J,4)
            ELSEIF(NODE_CT.EQ.CRACK_TIP_PAIR(J,4))THEN
                NODE_CT2=CRACK_TIP_PAIR(J,3)
            ENDIF
        ENDDO
        DO J=1,N_CRACKTIPS
            IF(CRACKTIP_COLLOCPOINTS(J).EQ.NODE_CT2)THEN
                POSITION_CT=J
            ENDIF
        ENDDO
!       CREATING VECTOR BETWEEN CRACK TIPS IN CRACK FRONT
        DO J=1,3
            VEC_CRACK(J)=COORD_CRACKTIP(I,J)-COORD_CRACKTIP(POSITION_CT,J)
        ENDDO
        CONTS=0
        CONTH=0
        DO J=1,SIZE(NC,1)
!           COLLOC_TEST STORES NUMBER OF CANDIDADE COLLOCATION POINT OF ALIGNMENT ELEMENT
            DO II=1,2
                COLLOC_TEST=NC(J,II)
                AUX1=0.D0
                DO K=1,3
                    VEC_AUX(K)=COORD_CRACKTIP(I,K)-COORD_COLLOCPOINTS(COLLOC_TEST,K)
                    AUX1=AUX1+VEC_CRACK(K)*VEC_AUX(K)
                ENDDO
                NORM_VEC_CRACK=DSQRT(VEC_CRACK(1)*VEC_CRACK(1)+VEC_CRACK(2)*VEC_CRACK(2)+VEC_CRACK(3)*VEC_CRACK(3))
                NORM_VEC_AUX=DSQRT(VEC_AUX(1)*VEC_AUX(1)+VEC_AUX(2)*VEC_AUX(2)+VEC_AUX(3)*VEC_AUX(3))
!               ALFA_VECS IS THE ANGLE BETWEEN VEC_CRACK AND VEC_AUX
                ALPHA_COS=AUX1/(NORM_VEC_CRACK*NORM_VEC_AUX)
                IF(ABS(ALPHA_COS).LT.1E-5)THEN
                    IF(DUAL_BEM(COLLOC_TEST).EQ."S")THEN
                        CONTS=CONTS+1
                        AUX_ALIGNMENT_NODE_S(CONTS)=COLLOC_TEST
                        AUX_ALIGNMENT_DIST_S(CONTS)=NORM_VEC_AUX
                    ELSEIF(DUAL_BEM(COLLOC_TEST).EQ."H")THEN
                        CONTH=CONTH+1
                        AUX_ALIGNMENT_NODE_H(CONTH)=COLLOC_TEST
                        AUX_ALIGNMENT_DIST_H(CONTH)=NORM_VEC_AUX
                    ENDIF
                ENDIF
            ENDDO
        ENDDO
!       ORGANIZING AUX IN ASCENDING ORDER
        DO II=1,SIZE(NC,1)
            DO JJ=1,II
                IF(AUX_ALIGNMENT_DIST_S(II).LT.AUX_ALIGNMENT_DIST_S(JJ))THEN
                    AUX1=AUX_ALIGNMENT_DIST_S(JJ)
                    AUX_ALIGNMENT_DIST_S(JJ)=AUX_ALIGNMENT_DIST_S(II)
                    AUX_ALIGNMENT_DIST_S(II)=AUX1
                    AUX_INT=AUX_ALIGNMENT_NODE_S(JJ)
                    AUX_ALIGNMENT_NODE_S(JJ)=AUX_ALIGNMENT_NODE_S(II)
                    AUX_ALIGNMENT_NODE_S(II)=AUX_INT
                ENDIF
                IF(AUX_ALIGNMENT_DIST_H(II).LT.AUX_ALIGNMENT_DIST_H(JJ))THEN
                    AUX1=AUX_ALIGNMENT_DIST_H(JJ)
                    AUX_ALIGNMENT_DIST_H(JJ)=AUX_ALIGNMENT_DIST_H(II)
                    AUX_ALIGNMENT_DIST_H(II)=AUX1
                    AUX_INT=AUX_ALIGNMENT_NODE_H(JJ)
                    AUX_ALIGNMENT_NODE_H(JJ)=AUX_ALIGNMENT_NODE_H(II)
                    AUX_ALIGNMENT_NODE_H(II)=AUX_INT
                ENDIF
            ENDDO
        ENDDO
    !   STORING ALIGNMENT INFORMATIONS
        DO II=1,N_ALIGNMENT_NODES
            ALIGN_ELEM_S_NODE(II,I)=AUX_ALIGNMENT_NODE_S(II)
            ALIGN_ELEM_H_NODE(II,I)=AUX_ALIGNMENT_NODE_H(II) 
        ENDDO
!       COMP_ALINGMENT_NODE STORES ALL NODES IN ALIGNMENT
        DO II=1,N_ENRICHED_ELEMS
            COMP_ALIGNMENT_NODE_S(II,I)=AUX_ALIGNMENT_NODE_S(II)
            COMP_ALIGNMENT_NODE_H(II,I)=AUX_ALIGNMENT_NODE_H(II)
        ENDDO
!       CALCULATING QSIS OF ALIGNMENT ELEMENT
        DX=COORD_CRACKTIP(I,1)-COORD_COLLOCPOINTS(ALIGN_ELEM_S_NODE(N_ALIGNMENT_NODES,I),1)
        DY=COORD_CRACKTIP(I,2)-COORD_COLLOCPOINTS(ALIGN_ELEM_S_NODE(N_ALIGNMENT_NODES,I),2)
        DZ=COORD_CRACKTIP(I,3)-COORD_COLLOCPOINTS(ALIGN_ELEM_S_NODE(N_ALIGNMENT_NODES,I),3)
        L_ELEM_S=DSQRT(DX*DX+DY*DY+DZ*DZ)
        DX=COORD_CRACKTIP(I,1)-COORD_COLLOCPOINTS(ALIGN_ELEM_H_NODE(N_ALIGNMENT_NODES,I),1)
        DY=COORD_CRACKTIP(I,2)-COORD_COLLOCPOINTS(ALIGN_ELEM_H_NODE(N_ALIGNMENT_NODES,I),2)
        DZ=COORD_CRACKTIP(I,3)-COORD_COLLOCPOINTS(ALIGN_ELEM_H_NODE(N_ALIGNMENT_NODES,I),3)
        L_ELEM_H=DSQRT(DX*DX+DY*DY+DZ*DZ)
        DO II=1,N_ALIGNMENT_NODES
!           ALIGNMENT ELEMENT WITH DISPLACEMENT EQN NODES (CRACK TIP HAS QSI=+1 IN THIS CASE)
            DX=COORD_CRACKTIP(I,1)-COORD_COLLOCPOINTS(ALIGN_ELEM_S_NODE(II,I),1)
            DY=COORD_CRACKTIP(I,2)-COORD_COLLOCPOINTS(ALIGN_ELEM_S_NODE(II,I),2)
            DZ=COORD_CRACKTIP(I,3)-COORD_COLLOCPOINTS(ALIGN_ELEM_S_NODE(II,I),3)
            L_NODE_CT=DSQRT(DX*DX+DY*DY+DZ*DZ)
            ALIGN_ELEM_S_QSI(II,I)=1-2*L_NODE_CT/L_ELEM_S
!           ALIGNMENT ELEMENT WITH TRACTION EQN NODES (CRACK TIP HAS QSI=-1 IN THIS CASE)
            DX=COORD_CRACKTIP(I,1)-COORD_COLLOCPOINTS(ALIGN_ELEM_H_NODE(II,I),1)
            DY=COORD_CRACKTIP(I,2)-COORD_COLLOCPOINTS(ALIGN_ELEM_H_NODE(II,I),2)
            DZ=COORD_CRACKTIP(I,3)-COORD_COLLOCPOINTS(ALIGN_ELEM_H_NODE(II,I),3)
            L_NODE_CT=DSQRT(DX*DX+DY*DY+DZ*DZ)
            ALIGN_ELEM_H_QSI(II,I)=-1+2*L_NODE_CT/L_ELEM_H            
        ENDDO
    ENDDO
!   FINDING ENRICHED ELEMENTS (LINEAR ONLY)
    ALLOCATE(ENRICHED_ELEMS(N_CRACKTIPS*N_ALIGNMENT_NODES/N_K,N_K+1))
    ENRICHED_ELEMS=0
    CONT=0
    DO J=1,N_ENRICHED_ELEMS
        DO I=1,N_ELEM
            NEN=ELEM_TYPE(K)*ORDER_ELEM(K)+(ELEM_TYPE(K)-3)*(ORDER_ELEM(K)-1)*POL_FAMILY(K)
            DO KK=1,NEN
                DO II=1,N_ALIGNMENT_NODES/2
                    IF(COLLOCPOINTS_CONNECTIVITY(I,KK).EQ.COMP_ALIGNMENT_NODE_S(2*II-1,2*J-1))THEN
                        CONT=CONT+1
!                       ELEMENT THAT CONTAINS ALIGN_ELEM_S_NODE
                        ENRICHED_ELEMS(CONT,1)=I
                        DO JJ=1,N_K
                            ENRICHED_ELEMS(CONT,JJ+1)=CRACK_TIP_PAIR(J,JJ+2)
                        ENDDO
                    ENDIF
                    IF(COLLOCPOINTS_CONNECTIVITY(I,KK).EQ.COMP_ALIGNMENT_NODE_H(2*II-1,2*J-1))THEN
                        CONT=CONT+1
!                       ELEMENT THAT CONTAINS ALIGN_ELEM_S_NODE
                        ENRICHED_ELEMS(CONT,1)=I
                        DO JJ=1,N_K
                            ENRICHED_ELEMS(CONT,JJ+1)=CRACK_TIP_PAIR(J,JJ+2)
                        ENDDO
                    ENDIF
                ENDDO
            ENDDO
        ENDDO
    ENDDO
!
    END SUBROUTINE XBEM_K_AUXILIAR_ELEMS

